### ISSUE TITLE
请问，镜像有支持arm的计划吗？

### ISSUE THREAD

**Issue by cellistV** [Guovin/iptv-api#369]
请问，镜像有支持arm的计划吗？ 感谢

**Comment by Guovin** [comment]
有的，预计下个版本支持

**Comment by cellistV** [comment]
Thx

**Comment by Guovin** [comment]
#374 已支持

**Comment by cellistV** [comment]
安装docker版本（arm）遇到如下错误


Sorting:   0%|          | 0/1131 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/tv-requests/main.py", line 273, in <module>
    scheduled_task()
  File "/tv-requests/main.py", line 259, in scheduled_task
    loop.run_until_complete(update_source.start())
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/tv-requests/main.py", line 244, in start
    await self.main()
  File "/tv-requests/main.py", line 173, in main
    self.channel_data = await process_sort_channel_list(
  File "/tv-requests/utils/channel.py", line 666, in process_sort_channel_list
    ffmpeg_installed = is_ffmpeg_installed()
  File "/tv-requests/utils/speed.py", line 40, in is_ffmpeg_installed
    result = subprocess.run(
  File "/usr/local/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'ffmpeg'

**Comment by Guovin** [comment]
> 安装docker版本（arm）运行后遇到如下错误
> 
> Sorting: 0%| | 0/1131 [00:00<?, ?it/s]Traceback (most recent call last): File "/tv-requests/main.py", line 273, in scheduled_task() File "/tv-requests/main.py", line 259, in scheduled_task loop.run_until_complete(update_source.start()) File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete return future.result() File "/tv-requests/main.py", line 244, in start await self.main() File "/tv-requests/main.py", line 173, in main self.channel_data = await process_sort_channel_list( File "/tv-requests/utils/channel.py", line 666, in process_sort_channel_list ffmpeg_installed = is_ffmpeg_installed() File "/tv-requests/utils/speed.py", line 40, in is_ffmpeg_installed result = subprocess.run( File "/usr/local/lib/python3.8/subprocess.py", line 493, in run with Popen(*popenargs, **kwargs) as process: File "/usr/local/lib/python3.8/subprocess.py", line 858, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "/usr/local/lib/python3.8/subprocess.py", line 1720, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) OSError: [Errno 8] Exec format error: 'ffmpeg'

是使用青龙吗？有人反馈使用最新版可以正常运行

**Comment by cellistV** [comment]
不是青龙，我用的是1panel

**Comment by Guovin** [comment]
看起来是ffmpeg版本不兼容arm64的原因，等我处理下

**Comment by Guovin** [comment]
#384 镜像更新了，再试试

**Comment by cellistV** [comment]
> #384 镜像更新了，再试试
谢谢，现在可以正常使用了
但是有个小问题。
到这一步“Total urls: 35930, need to sort: 1133”
CPU使用率会暴涨，卡死。
之后我限制了CPU使用数可以正常到导出结果。

**Comment by Guovin** [comment]
> > #384 镜像更新了，再试试
> > 谢谢，现在可以正常使用了
> > 但是有个小问题。
> > 到这一步“Total urls: 35930, need to sort: 1133”
> > CPU使用率会暴涨，卡死。
> > 之后我限制了CPU使用数可以正常到导出结果。

应该是ffmpeg测速并行的任务多导致，目前的测速效率比较激进，后续我增加调速配置解决这个问题

**Comment by joejoe0243** [comment]
Chrome driver 不能调用
Error on search: Message: Unable to obtain driver for chrome

**Comment by Guovin** [comment]
> Unable to obtain driver for chrome

什么运行平台？

**Comment by joejoe0243** [comment]
> > Unable to obtain driver for chrome
> 
> 什么运行平台？

RHEL

**Comment by cellistV** [comment]
> > > Unable to obtain driver for chrome
> > 
> > 
> > 什么运行平台？
> 
> RHEL 8.10

今天也遇到了这个问题

**Comment by Guovin** [comment]
> > > > Unable to obtain driver for chrome
> > > 
> > > 
> > > 什么运行平台？
> > 
> > 
> > RHEL 8.10
> 
> 今天也遇到了这个问题

拉取的是tv-driver镜像吗？该镜像内已经包含了driver，按理说容器启动应该不会出现这种情况。
请提供容器内的信息，容器内运行以下命令：
```bash
chromium --version
```
```bash
chromedriver --version
```

**Comment by cellistV** [comment]
> > > > > Unable to obtain driver for chrome
> > > > 
> > > > 
> > > > 什么运行平台？
> > > 
> > > 
> > > RHEL 8.10
> > 
> > 
> > 今天也遇到了这个问题
> 
> 拉取的是tv-driver镜像吗？该镜像内已经包含了driver，按理说容器启动应该不会出现这种情况。 请提供容器内的信息，容器内运行以下命令：
> 
> ```shell
> chromium --version
> ```
> 
> ```shell
> chromedriver --version
> ```

两个版本的镜像都测试过，问题是一样的
”Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver“

**Comment by Guovin** [comment]
> > > > > > Unable to obtain driver for chrome
> > > > > 
> > > > > 
> > > > > 什么运行平台？
> > > > 
> > > > 
> > > > RHEL 8.10
> > > 
> > > 
> > > 今天也遇到了这个问题
> > 
> > 
> > 拉取的是tv-driver镜像吗？该镜像内已经包含了driver，按理说容器启动应该不会出现这种情况。 请提供容器内的信息，容器内运行以下命令：
> > ```shell
> > chromium --version
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```shell
> > chromedriver --version
> > ```
> 
> 两个版本的镜像都测试过，问题是一样的 ”Unable to obtain driver for chrome; For documentation on this error, please visit: [https://www.selenium.dev/documentation/webdriver“](https://www.selenium.dev/documentation/webdriver%E2%80%9C)

请提供更多信息，按上述命令在容器内运行后查看输出，否则我无法排查问题原因，谢谢

**Comment by cellistV** [comment]
> > > > > > > Unable to obtain driver for chrome
> > > > > > 
> > > > > > 
> > > > > > 什么运行平台？
> > > > > 
> > > > > 
> > > > > RHEL 8.10
> > > > 
> > > > 
> > > > 今天也遇到了这个问题
> > > 
> > > 
> > > 拉取的是tv-driver镜像吗？该镜像内已经包含了driver，按理说容器启动应该不会出现这种情况。 请提供容器内的信息，容器内运行以下命令：
> > > ```shell
> > > chromium --version
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```shell
> > > chromedriver --version
> > > ```
> > 
> > 
> > 两个版本的镜像都测试过，问题是一样的 ”Unable to obtain driver for chrome; For documentation on this error, please visit: [https://www.selenium.dev/documentation/webdriver“](https://www.selenium.dev/documentation/webdriver%E2%80%9C)
> 
> 请提供更多信息，按上述命令在容器内运行后查看输出，否则我无法排查问题原因，谢谢

![Screenshot_2024-10-15-11-37-40-51_df198e732186825c8df26e3c5a10d7cd](https://github.com/user-attachments/assets/826d7bd2-1324-4138-9b5f-cac2d966bdb8)

**Comment by joejoe0243** [comment]
> > > > > Unable to obtain driver for chrome
> > > > 
> > > > 
> > > > 什么运行平台？
> > > 
> > > 
> > > RHEL 8.10
> > 
> > 
> > 今天也遇到了这个问题
> 
> 拉取的是tv-driver镜像吗？该镜像内已经包含了driver，按理说容器启动应该不会出现这种情况。 请提供容器内的信息，容器内运行以下命令：
> 
> ```shell
> chromium --version
> ```
> 
> ```shell
> chromedriver --version
> ```

```
chromium --version
Chromium 129.0.6668.100 built on Debian GNU/Linux 12 (bookworm)
chromedriver --version
ChromeDriver 129.0.6668.100 (cf58cba358d31ce285c1970a79a9411d0fb381a5-refs/branch-heads/6668@{#1704})
```

**Comment by Guovin** [comment]
@joejoe0243 @cellistV 建议先使用requests运行（修改config/config.ini配置：open_driver = False），这个问题我先研究下

**Comment by BenjiaH** [comment]
同请求支持arm/v7版docker

**Comment by Guovin** [comment]
> 同请求支持arm/v7版docker

新版v1.5.4已经支持arm v7
