### ISSUE TITLE
最佳配置实践

### ISSUE THREAD

**Issue by follin93** [Guovin/iptv-api#397]
如何配置才能获得最佳的电视体验，为什么跑出来的结果还是有很多源是几秒一卡的那种状态，有办法能避免么

**Comment by Guovin** [comment]
影响因素比较多，比如组播源会比酒店源稳定性差，你可以只获取酒店源。又或者你的网络支持ipv6，可以将接口协议类型ipv_type改为ipv6，ipv6会比ipv4更稳定流畅。
