### ISSUE TITLE
💯稳定的接口白名单分享💖

### ISSUE THREAD

**Issue by Guovin** [Guovin/iptv-api#514]
请将您认为稳定有效的频道接口分享出来，我将验证后添加至默认模板，大家一起实现更好的观看体验~

**Comment by li5bo5** [comment]
这两个个项目的都不错：
https://live.fanmingming.com/tv/m3u/ipv6.m3u
https://ghp.ci/https://raw.githubusercontent.com/joevess/IPTV/main/home.m3u8

**Comment by ahgu86** [comment]
白名单可以自行添添加省内的单播地址吗？

**Comment by Guovin** [comment]
> 白名单可以自行添添加省内的单播地址吗？

可以

**Comment by ahkfgu** [comment]
哪一个参数是添加白名单的？没有找到

**Comment by Guovin** [comment]
> 哪一个参数是添加白名单的？没有找到

白名单是针对单个频道接口进行设置，接口后加$!

**Comment by molun** [comment]
https://github.com/kimwang1978/collect-tv-txt
发现这个仓库资源挺多的

**Comment by Guovin** [comment]
> https://github.com/kimwang1978/collect-tv-txt 发现这个仓库资源挺多的

已在默认订阅中

**Comment by Kratos28** [comment]
https://www.gdtv.cn/tvChannelDetail/43 能从中抓取直播源吗?

**Comment by Guovin** [comment]
> https://www.gdtv.cn/tvChannelDetail/43 能从中抓取直播源吗?

不能

**Comment by njmaojing** [comment]
大佬，我fork项目后，跑出来的output/user_result.txt还是不太稳定呀，默认配置我改了ipv6优先，还有哪些可以优化的么
```
[Settings]
open_service = True
open_update = True
open_use_old_result = True
source_file = config/user_demo.txt
final_file = output/user_result.txt
open_online_search = False
online_search_page_num = 3
urls_limit = 30
open_keep_all = False
open_sort = True
sort_timeout = 10
open_ffmpeg = True
open_filter_resolution = True
min_resolution = 1920x1080
response_time_weight = 0.5
resolution_weight = 0.5
recent_days = 30
ipv_type = ipv6
ipv_type_prefer = IPv6
ipv4_num = 0
ipv6_num = 15
domain_blacklist = epg.pw,skype.serv00.net,iptv.yjxfz.com,live-hls-web-ajb.getaj.net,live.goodiptv.club,hc73k3dhwo5gfkt.wcetv.com,stream1.freetv.fun
open_m3u_result = True
url_keywords_blacklist = 
open_subscribe = True
subscribe_urls = http://175.178.251.183:6689/live.txt,http://102.134.54.106:3099/live/全国酒店源mini.txt,https://ghproxy.net/https://raw.githubusercontent.com/kimwang1978/collect-tv-txt/main/merged_output.txt,https://m3u.ibert.me/txt/fmml_dv6.txt,https://m3u.ibert.me/txt/o_cn.txt,https://m3u.ibert.me/txt/j_iptv.txt,https://github.moeyy.xyz/https://raw.githubusercontent.com/PizazzGY/TVBox/main/live.txt,https://ghproxy.net/https://raw.githubusercontent.com/xzw832/cmys/main/S_CCTV.txt,https://ghproxy.net/https://raw.githubusercontent.com/xzw832/cmys/main/S_weishi.txt,http://itv.22m.top/ITVBox/tv/tvonline.txt
open_multicast = True
open_multicast_tonkiang = True
open_multicast_fofa = True
multicast_region_list = 全部
multicast_page_num = 1
open_proxy = False
open_driver = True
open_hotel = True
open_hotel_tonkiang = True
open_hotel_fofa = True
hotel_region_list = 全部
hotel_page_num = 1
open_update_time = True
request_timeout = 10
origin_type_prefer = hotel,multicast,subscribe,online_search
hotel_num = 10
multicast_num = 10
subscribe_num = 10
online_search_num = 0
open_url_info = True
```

**Comment by Guovin** [comment]
@njmaojing 非本issue的问题请不要在此讨论，谢谢

**Comment by bboy2000** [comment]
https://github.com/vbskycn/iptv
https://github.com/asdjkl6/tv
https://github.com/jisoypub/iptv/blob/master/cn_all.m3u
这里面有不少直播源，筛选一下还是可以的

**Comment by hjs88** [comment]
能多添加潮汕地区的直播源吗

**Comment by haotiandao** [comment]
能不能把一个订阅的地址，所有源，优先排在最前面？

**Comment by nbqcw123** [comment]
https://ghgo.xyz/raw.githubusercontent.com/yuanzl77/IPTV/blob/main/live.txt
看下这个地址

**Comment by nbqcw123** [comment]
https://ghgo.xyz/raw.githubusercontent.com/yuanzl77/IPTV/master/live.txt
看下这个列表

**Comment by Guovin** [comment]
> https://ghgo.xyz/raw.githubusercontent.com/yuanzl77/IPTV/master/live.txt 看下这个列表

已添加至默认订阅

**Comment by nbqcw123** [comment]
https://ghgo.xyz/raw.githubusercontent.com/vbskycn/iptv/master/tv/hd.txt
又发现个列表，请测试

**Comment by Guovin** [comment]
> https://ghgo.xyz/raw.githubusercontent.com/vbskycn/iptv/master/tv/hd.txt 又发现个列表，请测试

这个跟默认订阅的https://live.zbds.top是一样的输出

**Comment by FRANKASEE** [comment]
http://aktv.top/live.txt
稳定的港澳台订阅，但会有被检测到的盗源的问题，播放软件直接添加播放没有问题

**Comment by Inliang** [comment]
https://github.com/iptv-org/iptv  发现一个，请测试

**Comment by Ceonta** [comment]
https://raw.githubusercontent.com/yuanzl77/IPTV/refs/heads/main/live.m3u
这个里面也很多

**Comment by Guovin** [comment]
转移至 #772
