### ISSUE TITLE
docker不支持ARM v7吗？

### ISSUE THREAD

**Issue by FRANKASEE** [Guovin/iptv-api#562]
欢迎使用 海纳思 32-bit 系统
          原创作者: 神雕Teasiu
          贡献者: Xjm MinaDee
          详细使用教程请浏览首页的《使用指南》
          访问我们的官网: https://www.ecoo.top

   板型名称 : Amlogic S805 OneCloud WS1608
   CPU 信息 : xunlei,onecloudamlogic,meson8b@4核处理器 | armv7l架构
   系统版本 : Ubuntu 20.04.6 LTS | V20240201-5.15.79-meson-32
   可用存储 : 42.7% 2572.0M 
   可用内存 : 45.4% 449.0M | 交换区：51.3% 262.0M 

root@hinas:~# docker pull dockerproxy.1panel.live/guovern/tv-driver:latest
latest: Pulling from guovern/tv-driver
no matching manifest for linux/arm/v7 in the manifest list entries

**Comment by FRANKASEE** [comment]
这是一个支持ARM的视频，可以参考一下

https://www.bilibili.com/video/BV1Se411Y7vJ/?spm_id_from=333.337.search-card.all.click&vd_source=a17287e10c6dc9bff0e38aad00062474

**Comment by BenjiaH** [comment]
同请求支持arm/v7版docker

**Comment by Guovin** [comment]
后续版本会提供支持

**Comment by FRANKASEE** [comment]
啥时候能安排上，玩客云在翘首期盼呢

**Comment by Guovin** [comment]
已支持ARM v7，请使用guovern/iptv-api镜像
