### ISSUE TITLE
接口输出格式问题

### ISSUE THREAD

**Issue by Vendong** [Guovin/iptv-api#581]
使用的是DOCKER形式，通过 8000端口访问。
目前可以在config.ini中定义使用M3U或是TXT形式输出。
是否可以做成两个接口？M3U和TXT接口分开。

**Comment by Guovin** [comment]
是有同时用两种结果的需求？

**Comment by Vendong** [comment]
是的。父母那边用DIYP的壳，方便看电视。 客厅用TVBOX。两个格式还不一样。

**Comment by ranapankj** [comment]
> 是有同时用两种结果的需求？
下了几个版本的tvbox发现m3u文件出现"|"这个符号会报错txt文件没问题
http://111.13.111.242/000000001000/3000000010000010833/index.m3u8?channel-id=FifastbLive&livemode=1&stbId=3&HlsProfileId=$订阅源|1920x1080

订阅源|1920x1080就中间那个“|”

**Comment by Guovin** [comment]
@Vendong @ranapankj 双结果API已实现，结果符号问题也修改，请更新v1.5.4
