### ISSUE TITLE
更新工具使用异常。扫描到了36项目就卡住了

### ISSUE THREAD

**Issue by Heiwk** [Guovin/iptv-api#583]
![145](https://github.com/user-attachments/assets/77289541-bda4-4d5d-b808-21083271dd25)
![Uploading 1q.png…]()
工具是新下载的直接电脑上面运行。卡在那个画面不动了
请教一下这是怎么回事啊，未改动任何文件。直接点开运行的

**Comment by Heiwk** [comment]
![Uploading 1q.png…]()

**Comment by Guovin** [comment]
图片都挂掉了，日志请复制文本发出来，应该不是卡住，而是访问限制了
