### ISSUE TITLE
现在的白名单添加单个频道问题

### ISSUE THREAD

**Issue by Satrorn** [Guovin/iptv-api#584]
1.模板频道接口地址后添加$!即可实现，现在只能一个个添加太麻烦，能否直接添加*.txt这样整个内容模式，我看之前也有人提过，还有我现在添加$!的源有些会过滤掉，我没设置过滤条件
2.关键字搜索是怎样设置的？

**Comment by Satrorn** [comment]
3.subscribe订阅源，除了填txt和m3u网址外，能否再增加一个内部文件夹，把一些已经下载或生成的txt和m3u文件放进去，更新时直接先读取这个文件夹的订阅源文件，再去读网址等，在网络不好的情况下，正常转换所需的频道

**Comment by Guovin** [comment]
1.后续会增加白名单文件
2.关键字是按模板的频道名称去搜索接口
3.这个不需要，你只需要将这些接口放到模板中即可

**Comment by w1365258** [comment]
> 1.后续会增加白名单文件 2.关键字是按模板的频道名称去搜索接口 3.这个不需要，你只需要将这些接口放到模板中即可

白名单添加需要绝对地址吗？还是像黑名单那样只要前缀。绝对地址确实太麻烦，一个一个添加

**Comment by Guovin** [comment]
> > 1.后续会增加白名单文件 2.关键字是按模板的频道名称去搜索接口 3.这个不需要，你只需要将这些接口放到模板中即可
> 
> 白名单添加需要绝对地址吗？还是像黑名单那样只要前缀。绝对地址确实太麻烦，一个一个添加

v1.5.6已更新，支持白名单关键字
