### ISSUE TITLE
本地docker和exe文件生成的结果很多都是超时

### ISSUE THREAD

**Issue by YOURDD** [Guovin/iptv-api#586]
已经设置了sort_timeout = 3，并且只选择IPV6节点和订阅源，生成出来的结果文件放在手机上的IPTV测试百分之80都是超时请问是什么原因

![7de3c75809f8044b2d7898072035a75](https://github.com/user-attachments/assets/85a86651-d375-4cde-abee-683c4eeff1ce)

放上完整的配置文件

[Settings]
open_service = True
open_update = True
open_use_old_result = True
source_file = config/demo.txt
final_file = output/result.txt
open_online_search = False
online_search_page_num = 1
urls_limit = 5
open_keep_all = False
open_sort = True
sort_timeout = 3
open_ffmpeg = True
open_filter_resolution = True
min_resolution = 1920x1080
response_time_weight = 0.5
resolution_weight = 0.5
recent_days = 30
ipv_type = IPv6
ipv_type_prefer = IPv6
ipv4_num = 0
ipv6_num = 5
open_m3u_result = False
url_keywords_blacklist = epg.pw,skype.serv00.net,iptv.yjxfz.com,live-hls-web-ajb.getaj.net,live.goodiptv.club,hc73k3dhwo5gfkt.wcetv.com,stream1.freetv.fun,zw9999.cnstream.top
	
open_subscribe = True
subscribe_urls = https://live.fanmingming.com/tv/m3u/ipv6.m3u,https://ghp.ci/https://raw.githubusercontent.com/joevess/IPTV/main/home.m3u8,https://aktv.top/live.txt,http://175.178.251.183:6689/live.txt,https://ghproxy.net/https://raw.githubusercontent.com/kimwang1978/collect-tv-txt/main/merged_output.txt,https://m3u.ibert.me/txt/fmml_dv6.txt,https://m3u.ibert.me/txt/o_cn.txt,https://m3u.ibert.me/txt/j_iptv.txt,https://github.moeyy.xyz/https://raw.githubusercontent.com/PizazzGY/TVBox/main/live.txt,https://ghproxy.net/https://raw.githubusercontent.com/xzw832/cmys/main/S_CCTV.txt,https://ghproxy.net/https://raw.githubusercontent.com/xzw832/cmys/main/S_weishi.txt,http://itv.22m.top/ITVBox/tv/tvonline.txt
	
open_multicast = False
open_multicast_foodie = True
open_multicast_fofa = True
multicast_region_list = 全部
multicast_page_num = 1
open_proxy = False
open_driver = False
open_hotel = False
open_hotel_foodie = True
open_hotel_fofa = True
hotel_region_list = 全部
hotel_page_num = 1
open_update_time = True
request_timeout = 5
origin_type_prefer = subscribe,multicast,hotel,online_search
hotel_num = 0
multicast_num = 0
subscribe_num = 5
online_search_num = 0
open_url_info = True
open_empty_category = False

而且本地支持IPV6，在不只使用IPV6的情况下会提示没有IPV6

**Comment by YOURDD** [comment]
> 这是旧版测速方法误差导致，更新v1.5.4再试试

更新了新版本，貌似找到了IPV6的bug，我网关填写的旁路由，旁路由上挂了科学，会导致检测不到IPV6并且结果文件全部都是空白。

![Snipaste_2024-12-01_23-19-25](https://github.com/user-attachments/assets/4382028c-7bf6-40ab-9808-c5b49591ae48)
![Snipaste_2024-12-01_23-19-10](https://github.com/user-attachments/assets/ef07172b-b324-4152-b81d-c9bda12e8363)
![Snipaste_2024-12-01_23-21-23](https://github.com/user-attachments/assets/b93cb34d-aa79-40fd-a7ad-ed6c9fcee9c8)


网关填写主路由的话就正常获取了，这个能不能改进一下。

![Snipaste_2024-12-01_23-18-07](https://github.com/user-attachments/assets/ee6d4460-dece-4503-a4b6-dba77f05ff98)

另外exe版本在测速阶段会连续跳出窗口的bug并且没有在测速。

![Snipaste_2024-12-01_23-17-34](https://github.com/user-attachments/assets/aa3d4baa-2200-4f36-8bcb-522fd13a2fa1)

**Comment by Guovin** [comment]
检测是否支持ipv6是取决于当前运行环境，如果你的网络支持ipv6，在更新时就不要开启代理等。
