### ISSUE TITLE
user_result.txt 文件只有标题，没有链接地址

### ISSUE THREAD

**Issue by VincentYangFan** [Guovin/iptv-api#587]
我这边生成的 user_result,txt 都是空的，内容如下：
root@armbian:/opt/iptv_api/output# cat user_result.txt 
更新时间,#genre#
2024-11-28 14:17:39,url
📺央视频道,#genre#

📡卫视频道,#genre#

☘️山东频道,#genre#

☘️安徽频道,#genre#

🌊港·澳·台,#genre#

🎬电影频道,#genre#

🎥咪咕直播,#genre#

🏀体育频道,#genre#

🪁动画频道,#genre#

🎮游戏频道,#genre#

🎵音乐频道,#genre#

🏛经典剧场,#genre#

user_result_log如下：
root@armbian:/opt/iptv_api/output# cat user_result.log 

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://172.31.0.2:8000
Press CTRL+C to quit
192.168.1.249 - - [28/Nov/2024 14:14:37] "GET / HTTP/1.1" 200 -
192.168.1.249 - - [28/Nov/2024 14:14:37] "GET /static/images/favicon.ico HTTP/1.1" 304 -
192.168.1.249 - - [28/Nov/2024 14:14:58] "GET / HTTP/1.1" 200 -
192.168.1.249 - - [28/Nov/2024 14:16:03] "GET / HTTP/1.1" 200 -
192.168.1.249 - - [28/Nov/2024 14:16:03] "GET /static/images/favicon.ico HTTP/1.1" 304 -
192.168.1.249 - - [28/Nov/2024 14:16:04] "GET / HTTP/1.1" 200 -
192.168.1.249 - - [28/Nov/2024 14:16:04] "GET /static/images/favicon.ico HTTP/1.1" 304 -
192.168.1.249 - - [28/Nov/2024 14:17:09] "GET / HTTP/1.1" 200 -
192.168.1.249 - - [28/Nov/2024 14:17:09] "GET /static/images/favicon.ico HTTP/1.1" 304 -

**Comment by Guovin** [comment]
请给出完整的docker容器运行日志
