### ISSUE TITLE
在本地运行main.py没有组播源和酒店源输出，只有选上订阅源才有输出，是怎么回事

### ISSUE THREAD

**Issue by hfgdv** [Guovin/iptv-api#588]
Processing fofa for hotel:  50%|█████     | 1/2 [01:27<01:27, 87.24s/it][Errno 2] No such file or directory: 'nul'
Processing fofa for hotel: 100%|██████████| 2/2 [04:56<00:00, 148.36s/it]
Loading local multicast rtp files:   0%|          | 0/1 [00:00<?, ?it/s][Errno 2] No such file or directory: 'nul'
Loading local multicast rtp files: 100%|██████████| 1/1 [00:00<00:00,  1.14it/s]
Processing fofa for multicast: 100%|██████████| 1/1 [00:00<00:00, 25.15it/s]
Multicast search:   0%|          | 0/1 [00:00<?, ?it/s][Errno 2] No such file or directory: 'nul'
Multicast search: 100%|██████████| 1/1 [00:00<00:00, 27.06it/s]
Foodie hotel search:   0%|          | 0/1 [00:00<?, ?it/s]广东电信:Error on search: [Errno 2] No such file or directory: 'nul'
广东:Error on search: [Errno 2] No such file or directory: 'nul'

**Comment by Guovin** [comment]
应该是访问限制导致没有结果返回
