### ISSUE TITLE
docker命令执行完怎么显示两个容器同时使用8000端口

### ISSUE THREAD

**Issue by xbwl486** [Guovin/iptv-api#591]
![18b36440e561a9634e72f240b21aa02](https://github.com/user-attachments/assets/274edd9a-da3e-4c61-a0cc-ddee2440652d)
同时显示两个容器，并且这两个只能运行一个不然显示8000端口被占用，这应该如何处理

**Comment by Guovin** [comment]
另一个容器设置不同的端口即可，转发内部的8000端口

**Comment by xbwl486** [comment]
大佬怎么操作呀，我在宝塔下载的docker
研究了一会没研究明白

**Comment by w1365258** [comment]
其实吧，端口开不开都无所谓，直接映射到宿主机路径www/ 下面就好，http://主机IP/你映射的文件夹（www不要填）/*.txt（或者*.m3u）

**Comment by Guovin** [comment]
> 大佬怎么操作呀，我在宝塔下载的docker 研究了一会没研究明白

启动容器时参数修改为8001:8000，8001为自定义端口
