### ISSUE TITLE
用docker更新了源，用potplayer播放问题

### ISSUE THREAD

**Issue by sgf2013sdo** [Guovin/iptv-api#595]
[trusting_gates.csv](https://github.com/user-attachments/files/17958218/trusting_gates.csv)
日志是这样的，但是播放的时候特别卡。一个频道更新了好几个地址
请问docker有什么命令和筛选低延迟的，并保留的命令吗？

**Comment by sgf2013sdo** [comment]
![image](https://github.com/user-attachments/assets/6b9c4807-7893-41a0-a327-2bbb576f46f3)
几乎一直在缓冲

**Comment by sgf2013sdo** [comment]
![image](https://github.com/user-attachments/assets/06f3fea9-f5ca-4b00-99b8-39d924b9e258)
群晖nas的docker里，这两个文件在哪找啊。大佬能告诉下吗

**Comment by Guovin** [comment]
频道是会有多个接口的，重复是因为软件问题，建议使用影迷、ok影视、tvbox等软件。结果文件可以使用挂载参数本地查看

**Comment by Vendong** [comment]
提取结果，文档里有写。
m3u格式   http://你的IP:8000/m3u
TXT格式    http://你的IP:8000/txt
