### ISSUE TITLE
希望能自定义端口

### ISSUE THREAD

**Issue by yf-9186** [Guovin/iptv-api#598]
本人采用docker方式部署，然后宿主机是有ipv6地址的，但是docker容器的bridge网络没开启ipv6支持。虽然查到了开启docker ipv6支持的配置方法，但还是希望docker部署的时候能够有一个环境变量配置来自定义端口，这样我就可以改用host网络

**Comment by Guovin** [comment]
修改容器启动命令即可，8001:8000，8001为自定义端口
