### ISSUE TITLE
建议内网源和通知

### ISSUE THREAD

**Issue by Satrorn** [Guovin/iptv-api#599]
1.建议订阅源是内网地址，192.168..的直接不测速放在最前面，如跟后面加的白名单重复就不建议了
2.后面可以考虑加个通知，微信，tg等，通知内容:频道开始更新，更新完成(上次频道数，新增频道数，本次更新总频道数)

**Comment by FRANKASEE** [comment]
通知还是不要了吧
通知需要添加api接口和toke，这个软件主要的目的是解决本地播放需要，有没有正常运行你打开电视就知道，通知有点画龙添足不说。还会增加代码量和docker文件大小。得不偿失

**Comment by Guovin** [comment]
目前只针对模板内容有白名单功能，没有单独针对单个订阅源的白名单，你可以将内网订阅源的内容复制到模板实现白名单。目前暂没有通知功能的计划。

**Comment by Satrorn** [comment]
内网订阅源的内容复制到模板,模板文件是哪个？rtp的也不是吧

**Comment by Guovin** [comment]
> 内网订阅源的内容复制到模板,模板文件是哪个？是指生成的tv.txt和m3u文件吗，这样每次都要手动，就不是每天测速更新有效源了.还有就是新版，我测试内网的源全部显示不出来，好像是过滤了，不知什么情况

模板文件是demo.txt，模板的作用是指定你想要频道内容，同时可以添加频道接口并设置白名单（更多见详细教程）。如果运行有问题请新建issue，并提交详细运行日志。

**Comment by Guovin** [comment]
v1.5.6已更新，已支持订阅源白名单 (config/whitelist.txt)
