### ISSUE TITLE
8000端口

### ISSUE THREAD

**Issue by charlie1227** [Guovin/iptv-api#605]
PVE--飞牛OS--docker部署，默认网络bridge，采集数据提示“不支持ipv6”，于是改用“host”，容器不断重启，日志显示“8000端口被占用”，经查，飞牛OS默认占用了8000端口作为访问入口。请问作者，本项目是否可以修改容器端口？

**Comment by Guovin** [comment]
修改启动命令，8001:8000，8001为自定义端口
