### ISSUE TITLE
新的IPTV-API在DOCKER下运行会被卡死，CPU占用高

### ISSUE THREAD

**Issue by liulei120** [Guovin/iptv-api#606]
如题，在进行测速排序时，CPU占用很高，最高会到140%左右。另外大概到排序1002条左右的时候就会被卡死，但是这个时候CPU占用率就会下降到百分之十几，我已经重启三次容器了，均是一样的情况。但之前老版本的就没有这个问题。
CPU占用截图：
![屏幕截图 2024-12-01 161723](https://github.com/user-attachments/assets/8500eca7-11f5-4a3f-9ab0-dd04025d6dcb)

容器内的执行日志截图：
![屏幕截图 2024-12-01 163214](https://github.com/user-attachments/assets/0b8e5f72-e765-404a-bf20-dace99466db0)

LOG.LOG文件的部分日志：

`
[0;31mERROR:[0m [generic] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)
[0;31mERROR:[0m [generic] Unable to download webpage: (<urllib3.connection.HTTPConnection object at 0x7fe75cfb7490>, 'Connection to 211.72.65.236 timed out. (connect timeout=10.0)') (caused by TransportError("(<urllib3.connection.HTTPConnection object at 0x7fe75cfb7490>, 'Connection to 211.72.65.236 timed out. (connect timeout=10.0)')"))
[0;31mERROR:[0m [generic] Unable to download webpage: (<urllib3.connection.HTTPConnection object at 0x7fe75cfb7490>, 'Connection to 120.84.96.87 timed out. (connect timeout=10.0)') (caused by TransportError("(<urllib3.connection.HTTPConnection object at 0x7fe75cfb7490>, 'Connection to 120.84.96.87 timed out. (connect timeout=10.0)')"))
[0;31mERROR:[0m [generic] Unable to download webpage: (<urllib3.connection.HTTPConnection object at 0x7fe75cfb7490>, 'Connection to 211.72.65.236 timed out. (connect timeout=10.0)') (caused by TransportError("(<urllib3.connection.HTTPConnection object at 0x7fe75cfb7490>, 'Connection to 211.72.65.236 timed out. (connect timeout=10.0)')"))
[0;31mERROR:[0m [generic] Unable to download webpage: (<urllib3.connection.HTTPConnection object at 0x7fe75cfb7230>, 'Connection to 211.72.65.236 timed out. (connect timeout=10.0)') (caused by TransportError("(<urllib3.connection.HTTPConnection object at 0x7fe75cfb7230>, 'Connection to 211.72.65.236 timed out. (connect timeout=10.0)')"))
[0;31mERROR:[0m [generic] Unable to download webpage: (<urllib3.connection.HTTPConnection object at 0x7fe75cfb6fd0>, 'Connection to 125.227.210.55 timed out. (connect timeout=10.0)') (caused by TransportError("(<urllib3.connection.HTTPConnection object at 0x7fe75cfb6fd0>, 'Connection to 125.227.210.55 timed out. (connect timeout=10.0)')"))
[0;31mERROR:[0m [generic] Unable to download webpage: (<urllib3.connection.HTTPConnection object at 0x7fe75cfb6d70>, 'Connection to 211.72.65.236 timed out. (connect timeout=10.0)') (caused by TransportError("(<urllib3.connection.HTTPConnection object at 0x7fe75cfb6d70>, 'Connection to 211.72.65.236 timed out. (connect timeout=10.0)')"))
`

**Comment by Guovin** [comment]
这是新的测速方法的问题，对于部分配置较低的设置有可能会出现这种情况，目前默认是开启了10个线程进行测速。

**Comment by Guovin** [comment]
我将在下版对该现象进行优化

**Comment by liulei120** [comment]
请问大佬，我修改了utils/channel.py里面的semaphore = asyncio.Semaphore(10)，将10修改为5，可以明显看出CPU占用比之前有所下降，但是程序运行到最后还是会卡死，麻烦请教一下是不是改错地方了？

另外硬件配置方面我是用服务器装的黑群晖然后运行的DOCKER，CPU优先级和内存都已经给到最大（4核至强+20G内存）。

**Comment by Guovin** [comment]
更新最新镜像再试试，看看cpu的情况如何，如果还是占用高的话，我后续会考虑增加并发配置

**Comment by liulei120** [comment]
目前在排序的时候CPU占用最高在60%左右，很完美。
