### ISSUE TITLE
docker部署生成result.m3u每个频道都有很多链接

### ISSUE THREAD

**Issue by bugensui2022** [Guovin/iptv-api#607]
比如cctv1频道他有很多链接，我家里是用kodi在电视上看的直播，你每个频道有很多链接，是需要我自己整理？还是部分软件可以实现选择最优的1条播放，我不太懂里面的逻辑，麻烦作者回复下，

**Comment by liulei120** [comment]
每个频道有很多链接的作用是可以实现线路切换功能，比如说安卓TV上用的DIYP就可以显示多个线路，但是KODI没用过，不知道能不能实现线路切换

**Comment by Guovin** [comment]
单个频道多个接口是为了避免单个接口失效而无法观看，建议使用tvbox等软件观看

**Comment by bugensui2022** [comment]
> 单个频道多个接口是为了避免单个接口故障而无法观看，建议使用tvbox等软件观看

可以自己设置成配置单个频道单个接口不，用习惯了kodi

**Comment by bugensui2022** [comment]
> 每个有很多链接的作用是可以实现线路切换功能，频道比如安卓电视上用的DIYP就可以显示多个线路，但是KODI没用过，不知道能不能实现线路切换

好的，谢谢，我研究下

**Comment by Guovin** [comment]
> > 单个频道多个接口是为了避免单个接口故障而无法观看，建议使用tvbox等软件观看
> 
> 可以自己设置成配置单个频道单个接口不，用习惯了kodi

可以的，你可以修改配置：urls_limit = 1即可实现

**Comment by bugensui2022** [comment]
> > > 单个频道多个接口是为了避免单个接口故障而无法观看，建议使用tvbox等软件观看
> > 
> > 
> > 可以自己设置成配置单个频道单个接口不，用习惯了kodi
> 
> 可以的，你可以修改配置：urls_limit = 1即可实现

好的，谢谢作者，终于给父母看电视找到了简单方案

**Comment by Inliang** [comment]
TVbox可以实现源整合，但是影视仓无法实现源整合
