### ISSUE TITLE
组播源失效

### ISSUE THREAD

**Issue by asxs123** [Guovin/iptv-api#615]
foodie_hotel_url = "http://www.foodieguide.com/iptvsearch/hoteliptv.php"链接失效了

湖南电信 page: 1 results num: 0
湖南电信:No results found
湖北联通 page: 1 results num: 0
湖北联通:No results found
重庆联通 page: 1 results num: 0
重庆联通:No results found
山东联通 page: 1 results num: 0
山东联通:No results found
浙江电信 page: 1 results num: 0
浙江电信:No results found
江苏电信 page: 1 results num: 0
江苏电信:No results found
河北联通 page: 1 results num: 0
河北联通:No results found
北京电信 page: 1 results num: 0

北京电信:No results found
四川电信 page: 1 results num: 0
四川电信:No results found
青海联通 page: 1 results num: 0
青海联通:No results found
海南电信 page: 1 results num: 0
海南电信:No results found
福建电信 page: 1 results num: 0
福建电信:No results found
内蒙古电信 page: 1 results num: 0
内蒙古电信:No results found
江西电信 page: 1 results num: 0
江西电信:No results found
山西电信 page: 1 results num: 0
山西电信:No results found
湖北电信 page: 1 results num: 0
湖北电信:No results found
重庆电信 page: 1 results num: 0
重庆电信:No results found
广东电信 page: 1 results num: 0
广东电信:No results found
天津联通 page: 1 results num: 0
天津联通:No results found
新疆电信 page: 1 results num: 0
新疆电信:No results found
河南联通 page: 1 results num: 0
河南联通:No results found
山东电信 page: 1 results num: 0
山东电信:No results found
安徽电信 page: 1 results num: 0
安徽电信:No results found
黑龙江联通 page: 1 results num: 0
黑龙江联通:No results found
云南电信 page: 1 results num: 0
云南电信:No results found
吉林电信 page: 1 results num: 0
吉林电信:No results found
河北电信 page: 1 results num: 0
河北电信:No results found
浙江联通 page: 1 results num: 0
浙江联通:No results found
上海电信 page: 1 results num: 0
上海电信:No results found
贵州电信 page: 1 results num: 0
贵州电信:No results found
北京联通 page: 1 results num: 0
北京联通:No results found
广西电信 page: 1 results num: 0
广西电信:No results found
天津电信 page: 1 results num: 0
天津电信:No results found
陕西电信 page: 1 results num: 0
陕西电信:No results found
山西联通 page: 1 results num: 0
山西联通:No results found
辽宁联通 page: 1 results num: 0
辽宁联通:No results found
甘肃电信 page: 1 results num: 0
甘肃电信:No results found
内蒙古联通 page: 1 results num: 0
内蒙古联通:No results found
宁夏电信 page: 1 results num: 0
宁夏电信:No results found
Foodie hotel search:   0%|          | 0/26 [00:00<?, ?it/s]
Foodie hotel search:   4%|▍         | 1/26 [00:27<11:19, 27.18s/it]
Foodie hotel search:   8%|▊         | 2/26 [00:30<05:11, 12.96s/it]
Foodie hotel search:  12%|█▏        | 3/26 [00:31<02:50,  7.43s/it]
Foodie hotel search:  15%|█▌        | 4/26 [01:02<06:15, 17.06s/it]
Foodie hotel search:  19%|█▉        | 5/26 [01:04<04:01, 11.50s/it]
Foodie hotel search:  23%|██▎       | 6/26 [01:05<02:36,  7.85s/it]
Foodie hotel search:  27%|██▋       | 7/26 [01:26<03:55, 12.38s/it]
Foodie hotel search:  31%|███       | 8/26 [01:28<02:42,  9.00s/it]
Foodie hotel search:  35%|███▍      | 9/26 [01:29<01:49,  6.43s/it]
Foodie hotel search:  38%|███▊      | 10/26 [01:51<03:00, 11.26s/it]
Foodie hotel search:  42%|████▏     | 11/26 [01:54<02:11,  8.78s/it]
Foodie hotel search:  46%|████▌     | 12/26 [01:55<01:28,  6.29s/it]
Foodie hotel search:  50%|█████     | 13/26 [02:17<02:22, 10.96s/it]
Foodie hotel search:  54%|█████▍    | 14/26 [02:19<01:40,  8.34s/it]
Foodie hotel search:  58%|█████▊    | 15/26 [02:19<01:05,  6.00s/it]
Foodie hotel search:  62%|██████▏   | 16/26 [02:41<01:47, 10.78s/it]
Foodie hotel search:  65%|██████▌   | 17/26 [02:45<01:16,  8.51s/it]
Foodie hotel search:  69%|██████▉   | 18/26 [02:46<00:50,  6.27s/it]
Foodie hotel search:  73%|███████▎  | 19/26 [03:13<01:27, 12.53s/it]
Foodie hotel search:  77%|███████▋  | 20/26 [03:16<00:58,  9.75s/it]
Foodie hotel search:  81%|████████  | 21/26 [03:18<00:37,  7.45s/it]
Foodie hotel search:  85%|████████▍ | 22/26 [03:38<00:44, 11.12s/it]
Foodie hotel search:  88%|████████▊ | 23/26 [03:41<00:26,  8.84s/it]
Foodie hotel search:  92%|█████████▏| 24/26 [03:42<00:13,  6.52s/it]
Foodie hotel search:  96%|█████████▌| 25/26 [04:02<00:10, 10.47s/it]
Foodie hotel search: 100%|██████████| 26/26 [04:06<00:00,  8.44s/it]
广东 page: 1 results num: 0
广东:No results found
北京 page: 1 results num: 0
北京:No results found
湖南 page: 1 results num: 0
湖南:No results found
湖北 page: 1 results num: 0
湖北:No results found
浙江 page: 1 results num: 0
浙江:No results found
上海 page: 1 results num: 0
上海:No results found
天津 page: 1 results num: 0
天津:No results found
江苏 page: 1 results num: 0
江苏:No results found
山东 page: 1 results num: 0
山东:No results found
河南 page: 1 results num: 0
河南:No results found
河北 page: 1 results num: 0
河北:No results found
山西 page: 1 results num: 0
山西:No results found
陕西 page: 1 results num: 0
陕西:No results found
安徽 page: 1 results num: 0
安徽:No results found
重庆 page: 1 results num: 0
重庆:No results found
福建 page: 1 results num: 0
福建:No results found
江西 page: 1 results num: 0
江西:No results found
辽宁 page: 1 results num: 0
辽宁:No results found
黑龙江 page: 1 results num: 0
黑龙江:No results found
吉林 page: 1 results num: 0
吉林:No results found
四川 page: 1 results num: 0
四川:No results found
云南 page: 1 results num: 0
云南:No results found
香港 page: 1 results num: 0
香港:No results found
内蒙古 page: 1 results num: 0
内蒙古:No results found
甘肃 page: 1 results num: 0
甘肃:No results found
海南 page: 1 results num: 0
海南:No results found

**Comment by Guovin** [comment]
并不是失效，而是该网站限制了访问，导致获取不到结果。你可以试一下本机访问查询也会大概率被限制请求的，目前默认配置已经关闭该来源，后续会移除该来源。
