### ISSUE TITLE
1.5.5版本DOCKER运行报错

### ISSUE THREAD

**Issue by liulei120** [Guovin/iptv-api#616]
日志提示：/bin/sh: 1: /iptv-api-entrypoint.sh: not found

已经把本地的容器、镜像都全部删除，完全重新拉取，拉取源为DOCKER HUB官方源。

**Comment by keluokeda** [comment]
+1

**Comment by keluokeda** [comment]
```
2024-12-02T12:33:25.858682072Z /bin/sh: 1: /iptv-api-entrypoint.sh: not found

```

**Comment by AlpacaBi** [comment]
我也遇到了这个问题。（ubuntu24.04  x86机器）

诡异的是，我直接把项目clone下来，在我本地linux服务器build了一下，发现刚刚build出来的本地镜像，创建的容器是正常运行的。

项目代码应该没问题，可能是dockerhub的镜像有问题？？？

**Comment by Guovin** [comment]
抱歉，由于更换编辑器静默修改了文件的行尾序列，导致文件无法识别，正在重新构建，等我重新上传镜像。

**Comment by liulei120** [comment]
感谢大佬的优质项目，已微信赞赏略表心意

**Comment by Guovin** [comment]
新镜像已经上传

**Comment by liulei120** [comment]
已重新拉取全量测试，完全正常，感谢大佬的辛苦付出
