### ISSUE TITLE
已用docker部署，在tvboxosc中要如何配置

### ISSUE THREAD

**Issue by eric-xdp** [Guovin/iptv-api#618]
大佬好，小白请教一下，需要如何配置tvboxosc，我在配置地址中填入http://ip:8000/txt，或者m3u，然后返回首页提示解析配置失败，点击直播都是提示频道列表为空。但是通过浏览器打开txt能看到已经更新完成了。如有打扰请见谅。第一次用tvboxosc

**Comment by Vendong** [comment]
方便截个图方便说明吗？

**Comment by Guovin** [comment]
可能你将直播源链接输入到数据源配置了

**Comment by eric-xdp** [comment]
前三张是TVBOXOSC的截图 。这个软件貌似智能输入这个配置地址这个地方：
![bf28ac89e5127bdaee8d023660dce19](https://github.com/user-attachments/assets/2647e4b6-f23f-4549-8433-16d3a7fa086e)
![cf15967997579edbf7e16ff0c6a1494](https://github.com/user-attachments/assets/a5f63526-e89c-4034-a5ba-7dd4af1fb18c)
![ac6b72620a15f25e10a2ac0f214d832](https://github.com/user-attachments/assets/f2672e7e-5d0a-4b63-a4cf-5286012fea2c)
底下这三张是TVBOX配置的截图：
![d786d70e6a757971e235c670051b522](https://github.com/user-attachments/assets/c269ecc6-8678-4fc1-87ef-8eba20e1b604)
![63271b654c60ef520b20451d9ad6bde](https://github.com/user-attachments/assets/3258f457-4c25-43f3-8e6a-77f251ba9940)
![ff2c67980593c3057dbfa4b0df013bf](https://github.com/user-attachments/assets/57609385-d901-4b1c-a5cc-8162cea943af)
我自己用docker部署的地址 ：http:ip:8000/txt 这里是有数据的如下：
[source.txt](https://github.com/user-attachments/files/17985816/source.txt)。配置：http:ip:8000/txt和采用大佬提供的代理地址都是出现如上图所示的情况。

**Comment by eric-xdp** [comment]
@Guovin @Vendong 两位大佬，已经贴图说明。感谢

**Comment by Guovin** [comment]
可以参考一下这个#398，我猜测有可能是tvbox无法识别更新时间分类导致的，你可以尝试将显示更新时间取消，open_update_time = False，重新运行输出的结果再试试

**Comment by eric-xdp** [comment]
我直接换了影视仓，只导入了直播源可以用了 。还有个问题请教一下 。 如果我docker部署的环境不支持ipv6的话，出来的源地址是不是只有ipv4的 。
