### ISSUE TITLE
这两天卡住了，请帮忙看看吧

### ISSUE THREAD

**Issue by alantang1977** [Guovin/iptv-api#621]
🥳 Update completed! Total time spent: 09:48. Please check the output/user_result.txt file!

这两天卡住了，请帮忙看看吧

**Comment by Guovin** [comment]
请给出详细问题描述与日志

**Comment by alantang1977** [comment]
![微信截图_20241203174605](https://github.com/user-attachments/assets/9065ba9f-8582-4357-ab63-dc19f714c682)
就图片情况，我也不清楚是那有问题！

**Comment by Guovin** [comment]
貌似是已经更新完成了，但工作流并没有进入下一个流程，具体我去排查下原因

**Comment by hllkk** [comment]
@Guovin 大神，我发现个中端倪，当一个链接为播放列表时，会导致程序卡住，比如URL：http://zsntlqj.xicp.net:8896/bysid/83.m3u8 直接调用get_speed就会卡住，得一个多小时即便异步任务执行完毕，也会让程序卡住。

**Comment by solo30years** [comment]
来信收到 谢谢

**Comment by Guovin** [comment]
> @Guovin 大神，我发现个中端倪，当一个链接为播放列表时，会导致程序卡住，比如URL：http://zsntlqj.xicp.net:8896/bysid/83.m3u8 直接调用get_speed就会卡住，得一个多小时即便异步任务执行完毕，也会让程序卡住。

感谢提供链接，之前我就发现了某些链接在被yt_dlp调用时会出现类似的问题，但一直找不出这些链接。之前使用多线程调用yt_dlp出现了这种问题，会卡在某些链接，出现后台线程无限下载的情况。尽管只是使用extract_info(url, download=False)，也已经跳过了下载。后来改成异步超时中断处理，以为解决了，但最近还是出现了这种情况。我查看了yt_dlp的文档，可惜的是没有提供类似超时处理的参数设置和方法，这也应该是yt_dlp的bug，似乎也没有人对这个问题在yt_dlp提出过类似的issue。在yt_dlp没有解决这个bug之前，我觉得可以分析下这类链接的共同独有特征，在测速前过滤掉，避免对这类链接进行yt_dlp的处理。

**Comment by Guovin** [comment]
> 那如何解决呢，不太懂，哈哈

可以先将这个链接加入黑名单配置（url_keywords_blacklist）

**Comment by Guovin** [comment]
该问题工作流已经解决，请更新最新代码，其它模式需要等待下版更新

**Comment by zg4321** [comment]
> 该问题工作流已经解决，请更新最新代码，其它模式需要等待下版更新

辛苦了

**Comment by Vendong** [comment]
> 该问题工作流已经解决，请更新最新代码，其它模式需要等待下版更新

我自己的经验是，做个看门狗，超时直接杀进程

**Comment by Guovin** [comment]
v1.5.6已更新，该问题已修复。由于yt-dlp维护人员认为触发该问题是一个“非法”的链接，不予以支持并解答。目前已移除使用yt-dlp，改用其它方法实现。
