### ISSUE TITLE
docker配置下去掉m3u头部的更新时间的参数是哪个？

### ISSUE THREAD

**Issue by bugensui2022** [Guovin/iptv-api#622]
大佬，看了您的官方文档，参数说明，没有看明白，docker支持吗？生成结果顶部有更新时间，在kodi里播放，顶部的更新时间会占一位，导致播放出错，想去掉，另外默认一个频道是10个播放源，我改urls_limit = 1，这样是生成1个播放源，他的程序逻辑是10个里面质量最高的1个播放源吗？

**Comment by Guovin** [comment]
更新时间显示配置：open_update_time = False
是的，默认第一位的是最佳的接口

**Comment by bugensui2022** [comment]
> 更新时间显示配置：open_update_time = False 是的，默认第一位的是最佳的接口

看到了，谢谢，您在参数文档里并没有open_update_time 的相关说明，建议大佬写上，方便新手，

**Comment by Guovin** [comment]
> > 更新时间显示配置：open_update_time = False 是的，默认第一位的是最佳的接口
> 
> 看到了，谢谢，您在参数文档里并没有open_update_time 的相关说明，建议大佬写上，方便新手，

好的，后续我会补充

**Comment by zg4321** [comment]
可以把更新时间放到最后吗

**Comment by Guovin** [comment]
> 可以把更新时间放到最后吗

后面会增加配置调整更新时间位置

**Comment by Guovin** [comment]
v1.5.6已更新，文档已更新。
