### ISSUE TITLE
这个是什么情况，运行到这里就不动了

### ISSUE THREAD

**Issue by zg4321** [Guovin/iptv-api#623]
![1733235554431](https://github.com/user-attachments/assets/1b1852c6-c7df-4eb5-82c4-8be17ed616dd)

**Comment by zg4321** [comment]
![dde193207bf4af69cb0039ccec3185e](https://github.com/user-attachments/assets/23500bca-0915-4076-a250-e31fcc000f2e)


Traceback (most recent call last):
File "threading.py", line 104l, in _bootstrap_inner
File "threading.py", line 992, in run
File"tkinter_ui\tkinter_ui.py, line 119, in run_loop
File “asyncio\base_events. py", line 721, in run_unti1_complete
File ”tkinter_ui\tkinter_ui.py", line 104, in run_update
File "main.py line 197, in start
File main.py, line 149, in main
File “utils\channel. py , line 618, in write_channel_to_file
File "utils\tools.py, line 520, in write_content_into_txt

PermissionError:[Errno 13] Permission denied:'output/result_new.txt’

Writing: 2%
 77/3286 [00:13<00:24,130.40it/s]

**Comment by Guovin** [comment]
尝试以管理员方式运行？

**Comment by zg4321** [comment]
> 尝试以管理员方式运行？
不是管理员方式运行的问题，不知道是什么情况，不过找到能用的方法了，把电脑重启完立马再运行就没这个问题，过一会再次运行就不行了。
