### ISSUE TITLE
接口在IOS  Senplayer软件上无法导入

### ISSUE THREAD

**Issue by gxterry** [Guovin/iptv-api#632]
如题，使用url或文件无论是m3u还是txt均无法导入
提示 url解析失败，请检查网络
另外一个项目的m3u导入正常
如可能辛苦作者看看为啥

**Comment by Guovin** [comment]
可能是更新时间格式软件无法识别，建议关闭显示更新时间后再试试（open_update_time = False）

**Comment by Vendong** [comment]
还有一种可能。 测试发现返回的结果文件，头部有  “<head><link rel='icon' href='/static/images/favicon.ico' type='image/x-icon'></head><pre>”  。

**Comment by Guovin** [comment]
> 还有一种可能。 测试发现返回的结果文件，头部有 `<head><link rel='icon' href='/static/images/favicon.ico' type='image/x-icon'></head>\<pre\>`

你确定你的txt或m3u文件内有这种内容吗？这是网页的源码格式，应该不会影响。

**Comment by Vendong** [comment]
> > 还有一种可能。 测试发现返回的结果文件，头部有 `<head><link rel='icon' href='/static/images/favicon.ico' type='image/x-icon'></head>\<pre\>`
> 
> 你确定你的txt或m3u文件内有这种内容吗？这是网页的源码格式，应该不会影响。

![image](https://github.com/user-attachments/assets/fcd18b76-6fb7-433e-9b23-7abbb6e123a7)
这是DIYP导入txt后的显示，可以明确看出TXT接口中带了网页源码。 
不过不清楚SENPLAYER软件中是不是这个原因引起的异常。

IOS中还是推荐用ntPlayer导入m3u接口观看IPTV，我自己使用ntPlayer没有问题。

**Comment by Guovin** [comment]
> > > 还有一种可能。 测试发现返回的结果文件，头部有 `<head><link rel='icon' href='/static/images/favicon.ico' type='image/x-icon'></head>\<pre\>`
> > 
> > 
> > 你确定你的txt或m3u文件内有这种内容吗？这是网页的源码格式，应该不会影响。
> 
> ![image](https://private-user-images.githubusercontent.com/24760638/393746333-fcd18b76-6fb7-433e-9b23-7abbb6e123a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MzMxNzYsIm5iZiI6MTczMzczMjg3NiwicGF0aCI6Ii8yNDc2MDYzOC8zOTM3NDYzMzMtZmNkMThiNzYtNmZiNy00MzNlLTliMjMtN2FiYmI2ZTEyM2E3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDA4Mjc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNmJmMjgxYTI5NThjMWQyMTI0NjQ0MjY2M2YzNTgzMTM1OWJiZmI1MjUzZGJlMGI3YjJhYjc4MTM5MzU3NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gPtV24_aNea9lJA_u_SlQ_-IWUJ0yw4Lehb687ZzN_o) 这是DIYP导入txt后的显示，可以明确看出TXT接口中带了网页源码。 不过不清楚SENPLAYER软件中是不是这个原因引起的异常。
> 
> IOS中还是推荐用ntPlayer导入m3u接口观看IPTV，我自己使用ntPlayer没有问题。

有可能是部分播放器以源码形式进行解析结果了
