### ISSUE TITLE
使用vlc所有地址几乎都很卡顿

### ISSUE THREAD

**Issue by jkhAIjava** [Guovin/iptv-api#634]
我用vlc，试了很多地址，几乎都很卡顿，十几秒加载一小段视频。家里的网200M电信，应该不存在网速慢的原因，请问各位大佬是什么情况

**Comment by Guovin** [comment]
使用的结果是你本地网络运行的结果吗？取决于接口本身质量以及与你的网络有关。

**Comment by Vendong** [comment]
最近也发现了，fanmingming源里的地址，我这里直接用速度很快。  但是测速结果里总是几个速度一般的，而不采用fanmingming源。

**Comment by Guovin** [comment]
> 最近也发现了，fanmingming源里的地址，我这里直接用速度很快。 但是测速结果里总是几个速度一般的，而不采用fanmingming源。

结果顺序取决于当时运行的测速排序，如果生成结果运行环境和你使用播放的网络环境不一致，也会有影响。如果你想固定某些接口跳过测速保留在最前，可以使用白名单，详见详细教程

**Comment by Guovin** [comment]
同时，每个接口不可能时刻都能保持流畅播放，这是接口本身的原因
