### ISSUE TITLE
如何使用源自带的模版？

### ISSUE THREAD

**Issue by alasion** [Guovin/iptv-api#635]
目前使用的订阅源订阅链接经常更新，局域网内多台设备都使用IPTV，为了方便管理，在NAS上搭建了iptv-api服务，但是不知道如何使用订阅源自带的模版。

尝试一：删除demo.txt，程序运行会自动生成。
尝试二：删除demo.txt内容，生成的result.m3u也是空白。
尝试三：按照订阅源的内容手动编辑demo.txt，原本的一个频道会变成三个；而且频道栏目太多，全部手动添加不现实。

请问有没有方法可以直接调用订阅源自带的模版？

**Comment by Guovin** [comment]
我不是很清楚你的需求是什么，输出结果取决于你的模板文件，如果你想要某个订阅源的格式，直接copy至demo.txt不就好了？

**Comment by Guovin** [comment]
模板格式目前只支持txt，未支持m3u。

**Comment by alasion** [comment]
感谢，目前只能先手动替换了，期待后续更新。
