### ISSUE TITLE
一直执行不起来，lite版本，用标准版好像也不行

### ISSUE THREAD

**Issue by Andy-Home** [Guovin/iptv-api#636]
[2024_12_9 13_52_58_log.txt](https://github.com/user-attachments/files/18056923/2024_12_9.13_52_58_log.txt)

**Comment by Guovin** [comment]
duplicate #585

**Comment by Guovin** [comment]
升级docker到23.0.0以上的版本

**Comment by Guovin** [comment]
重复问题请不要多次创建，上一个问题已经等待许久未回复后已经关闭了，这个问题请尽快回复，否则多次邮件提醒会造成打扰，严重会阻止使用仓库。

**Comment by Andy-Home** [comment]
升级Docker后已经运行起来，非常感谢
