### ISSUE TITLE
如何设置更智能分类，如咪咕下列表，IPV6下列表

### ISSUE THREAD

**Issue by alantang1977** [Guovin/iptv-api#637]
如何设置更智能分类，如咪咕下列表，IPV6下列表

如下链接分类，能识别出来吗？
https://www.mytvsuper.com.mp/m3u/Live.m3u

**Comment by Guovin** [comment]
分类指的是？这个地址作为订阅源我试了是可以获取结果的

**Comment by Guovin** [comment]
没有看到你的回复，如果没有问题，我将关闭这个issue
