### ISSUE TITLE
无法获取到ipv4源

### ISSUE THREAD

**Issue by shenmadouyaowen** [Guovin/iptv-api#638]
大佬，我这个配置为什么无法获取ipv4地址的源，只能获取ipv6,刚开始默认你的配置也是一样
获取空白
![image](https://github.com/user-attachments/assets/232b453d-e408-43b5-aae0-7b770128c4f2)

config 配置：
![image](https://github.com/user-attachments/assets/4655c42d-37fc-4bbc-a0fe-cdf4b410a694)

下面是1000条docker 日志
[_flamboyant_chaplygin_logs.txt](https://github.com/user-attachments/files/18059892/_flamboyant_chaplygin_logs.txt)

**Comment by Guovin** [comment]
检查一下log.log和sort.log日志文件，应该是测速出了问题

**Comment by shenmadouyaowen** [comment]
> sort

谢谢大佬，是玩客云网络问题

**Comment by FRANKASEE** [comment]
> > sort
> 
> 谢谢大佬，是玩客云网络问题

我的设备也是玩客云，请问是如何解决的？

**Comment by shenmadouyaowen** [comment]
> > > sort
> > 
> > 
> > 谢谢大佬，是玩客云网络问题
> 
> 我的设备也是玩客云，请问是如何解决的？

我也解决不了，没用了
