### ISSUE TITLE
直播源加载报错：javax.net.ssl.SSLHandshakeException: Received fatal alert: protocol_version

### ISSUE THREAD

**Issue by shareworker** [Guovin/iptv-api#639]
Android4系统默认不启用TLSv1.1 和 TLSv1.2 协议，而新使用的CDN加速代理只支持TLSv1.2 协议，建议更换CDN代理，比如更换为：https://cdn.jsdelivr.net/gh/Guovin/iptv-api@gd/output/result.txt

**Comment by Guovin** [comment]
jsdelivr国内使用出现过不稳定的情况，需要处理缓存更新。

**Comment by Guovin** [comment]
v1.5.6已更新，已替换为jsdelivr代理。
