### ISSUE TITLE
如何将本地docker运行的肥羊项目本地源，添加到最终的测试结果中？

### ISSUE THREAD

**Issue by FRANKASEE** [Guovin/iptv-api#641]
目前在本地主机上运行肥羊docker项目，会生成一个本地文件：192.168.6.x：35455/tv.m3u，
m3u内的地址是192.168.6.X：35455/xxx/m3u，
这些源如果手动添加到dome文件内，就不会参加测速，但这些文件中可能会有一个或者两个无效源，
如果不加入dome使用白名单规则，就会无法测试

肥羊项目地址：https://hub.docker.com/r/youshandefeiyang/allinone/tags

**Comment by Guovin** [comment]
将文件地址添加至订阅配置中即可，同时保持模板文件中有你想要的频道

**Comment by FRANKASEE** [comment]
测试了多次，好像还是不行，具体看图片和附件

**Comment by FRANKASEE** [comment]
![screenshot_2024-12-11_09-16-29](https://github.com/user-attachments/assets/31c4c497-c7a3-48bb-b587-a31c59ab6ba0)
![screenshot_2024-12-11_09-17-09](https://github.com/user-attachments/assets/1f872e47-aafc-4de3-ad0d-31e87ada8eb3)
![BF8E2066-8EDE-41bc-8D4A-73DEC2C0E9E3](https://github.com/user-attachments/assets/a66a003d-4bd1-49fd-a881-5ecb2afd0868)

**Comment by FRANKASEE** [comment]
[log.log](https://github.com/user-attachments/files/18088142/log.log)
[demo.txt](https://github.com/user-attachments/files/18088146/demo.txt)
[config.txt](https://github.com/user-attachments/files/18088153/config.txt)

日志和配置文件

**Comment by FRANKASEE** [comment]
同样的配置，使用win10桌面运行EXE文件，出来的结果没有问题

**Comment by Guovin** [comment]
url_keywords_blackList是黑名单，不是白名单！接口白名单目前只能单个频道接口定义在模板文件中，具体参见详细教程。

**Comment by Guovin** [comment]
如果你想要订阅其中的结果，需要添加到subscribe_urls中

**Comment by FRANKASEE** [comment]
> url_keywords_blackList是黑名单，不是白名单！接口白名单目前只能单个频道接口定义在模板文件中，具体参见详细教程。

我没有设置接口白名单，我是把不想参加测试的直播源直接设置在dome文件内了。黑名单也没有添加这些ip和域名

**Comment by FRANKASEE** [comment]
收藏台,#genre#
CCTV-1_综合,http://192.168.6.158:35455/tptv/G_CCTV-1-AVS-4K264.m3u8
CCTV-2_财经,
CCTV-3_综艺,http://192.168.6.158:35455/tptv/G_CCTV-3-AVS-4K264.m3u8
CCTV-4_中文国际,
CCTV-5_体育,http://192.168.6.158:35455/tptv/G_CCTV-5-AVS-4K264.m3u8

**Comment by Guovin** [comment]
你还是没理解黑名单和白名单是什么意思，白名单是不参加测速排序结果保留在最终结果的最前面，黑名单是结果中过滤这些地址。我看到你黑名单添加了一些本地的ip地址，只要接口含有这些地址就会被忽略，不会被添加到结果中。如果你想要不参加测速而保留在最终结果，则是使用白名单，白名单的具体使用已经在详细教程说明了。

**Comment by Guovin** [comment]
如果已经理解清楚，没有更多问题，我将关闭这个issue

**Comment by FRANKASEE** [comment]
我还是没有搞清楚现在的白名单具体是怎么操作，难道不是在dome文件内添加吗？

**Comment by FRANKASEE** [comment]
我上传的dome文件内添加的带地址的直播源，是添加的方式错误还是添加缺少符号？

**Comment by FRANKASEE** [comment]
那为什么用win10桌面的exe生成的结果又包含了我添加进去的直播源呢

**Comment by FRANKASEE** [comment]
> 你还是没理解黑名单和白名单是什么意思，白名单是不参加测速排序结果保留在最终结果的最前面，黑名单是结果中过滤这些地址。我看到你黑名单添加了一些本地的ip地址，只要接口含有这些地址就会被忽略，不会被添加到结果中。如果你想要不参加测速而保留在最终结果，则是使用白名单，白名单的具体使用已经在详细教程说明了。

搜索了一下，没有找到白名单的教程

我还是没有搞清楚现在的白名单具体是怎么操作，难道不是在dome文件内添加吗？

我上传的dome文件内添加的带地址的直播源，是添加的方式错误还是添加缺少符号？

**Comment by FRANKASEE** [comment]
我的目的只是想把：CCTV-1_综合,http://192.168.6.158:35455/tptv/G_CCTV-1-AVS-4K264.m3u8，这样的地址设置不参加测速且保留在生成的最终结果内CCTV-1的第一个位置

**Comment by Guovin** [comment]
为什么会没找到？搜索白名单就看到了。
如果需要将该接口设为白名单（不测速、保留在结果最前），可在地址后添加$!即可，例如：http://xxx$!
后面也可以添加额外说明信息，如：http://xxx$!白名单接口

**Comment by FRANKASEE** [comment]
我再测试一次结果看看

**Comment by FRANKASEE** [comment]
按照你的这个现在可以正常使用白名单了
