### ISSUE TITLE
请问下docker应该怎么使用

### ISSUE THREAD

**Issue by J2ane** [Guovin/iptv-api#644]
### Occurrence environment

- [ ] Workflow
- [ ] GUI
- [X] Docker
- [ ] Command line

### Question description

请问下docker版本应该怎么使用？我已从8000端口下下载m3u，但是没办法通过使用vlc进行播放。
一般docker的操作整个流程是啥？docker默认安装后运行在8000端口下载后的m3u还需要进行操作吗

**Comment by Guovin** [comment]
不需要进行额外操作，一般是播放器问题，更换播放器加载m3u结果

**Comment by J2ane** [comment]
> 不需要进行额外操作，一般是播放器问题，更换播放器加载m3u结果

好的，谢谢，我试下别的播放器。
