### ISSUE TITLE
增加源地址前缀排序优先

### ISSUE THREAD

**Issue by w1365258** [Guovin/iptv-api#646]
因为每个地区的网络环境不同，导致测试的网速不一致，强烈推荐增加这个功能需（True False）要用户自行测试，比方说我所在地区前缀http://1.2.3……网速快，优先排第一，http://1.2.4……也不错，排第二。（前提是源里有这些地址前缀，当然，既然是自己选择的，肯定测试过的）

**Comment by w1365258** [comment]
好吧，问一下。如何添加关键字搜索？

**Comment by Guovin** [comment]
> 好吧，问一下。如何添加关键字搜索？

开启关键字搜索open_online_search = True，会按模板中的频道逐个进行查询，一般不建议开启，会大幅增加查询时间。

**Comment by w1365258** [comment]
感谢你的回复，我的意思是在哪输入关键词

**Comment by Guovin** [comment]
> 感谢你的回复，我的意思是在哪输入关键词

关键字白名单？目前还不支持
