### ISSUE TITLE
小白求问几个问题

### ISSUE THREAD

**Issue by weirui88888** [Guovin/iptv-api#648]
小白，求助各位大佬，几个问题

1.大佬你们口中说的影视仓的地址是：https://github.com/o0HalfLife0o/TVBoxOSC 这个吗~

2.是数据源固定用https://ghp.ci/raw.githubusercontent.com/Guovin/iptv-api/gd/source.json，然后接口源用通过workflow跑出来的user_result.txt吗？

3.是用影视仓，然后分别配这两个地址是吗？

4.在配好的前提下，是不是既能看那些直播，比如CCTV,央视等，也能看那些网上的电视剧和电影啥的~

**Comment by Guovin** [comment]
请使用提供的Question模板创建issue，不要使用空白模板，否则不予处理，谢谢

**Comment by KKL369** [comment]
建议多看教程，配合自己理解

**Comment by weirui88888** [comment]
> 请使用提供的Question模板创建issue，不要使用空白模板，否则不予处理，谢谢

我刚开始是通过那个的，但是不给我提交，谢谢。

**Comment by weirui88888** [comment]
> 建议多看教程，配合自己理解

好的，谢谢。

**Comment by Guovin** [comment]
> > 请使用提供的Question模板创建issue，不要使用空白模板，否则不予处理，谢谢
> 
> 我刚开始是通过那个的，但是不给我提交，谢谢。

有红点的要注意查看并勾选确认才能提交的
