### ISSUE TITLE
请问下看电视的时候网络特别慢，是视频源问题还是我网络设置问题，电视下载速度都跑不满1兆

### ISSUE THREAD

**Issue by wwwrookie** [Guovin/iptv-api#656]
### Don't skip these steps

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field
- [X] I have checked through the search that there are no similar issues that already exist
- [X] I will not submit any issues that are not related to this project

### Occurrence environment

- [ ] Workflow
- [ ] GUI
- [X] Docker
- [ ] Command line

### Question description

请问下看电视的时候网络特别慢，是视频源问题还是我网络设置问题，电视下载速度都跑不满1兆

### Related log

```shell
运行在docker中
```

**Comment by Guovin** [comment]
这跟源本身有很大关系，如果你的网络质量好，但播放不佳，可能是源当前访问观看人数较多，高峰导致卡顿。

**Comment by wwwrookie** [comment]
好的  我自己的电脑下载能跑50兆 可能就是源的问题吧
