### ISSUE TITLE
请问白名单如何使用？

### ISSUE THREAD

**Issue by zhycn9033** [Guovin/iptv-api#679]
### Don't skip these steps

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field
- [X] I have checked through the search that there are no similar issues that already exist
- [X] I will not submit any issues that are not related to this project

### Occurrence environment

- [X] Workflow
- [ ] GUI
- [ ] Docker
- [ ] Command line

### Question description

我在user_demo.txt里写的白名单接口“斗地主,https://www.goodiptv.club/huya/jjworld$!”，貌似还是参与测速了，并没有出现在最终结果文件里

**Comment by Guovin** [comment]
我使用你的模板和配置尝试运行了几次，并没有复现，你更新最新代码再试试？

**Comment by Guovin** [comment]
现在可以也使用whitelist.txt更方便地配置白名单了

**Comment by zhycn9033** [comment]
刚才又跑了一次，跑之前也更新代码了，白名单的接口在user_demo.txt和whitelist.txt里都填写了，结果依然没有出现这些白名单接口

**Comment by zhycn9033** [comment]
`[Settings]
open_service = True
open_update = True
open_use_old_result = False
open_use_cache = True
open_request = False
source_file = config/user_demo.txt
final_file = output/user_result.txt
open_online_search = False
online_search_page_num = 1
urls_limit = 20
open_keep_all = False
open_sort = True
sort_timeout = 10
open_ffmpeg = True
open_filter_speed = False
min_speed = 0.2
open_filter_resolution = False
min_resolution = 1920x1080
delay_weight = 0.25
speed_weight = 0.5
resolution_weight = 0.5
recent_days = 30
ipv_type = IPv4
ipv_type_prefer = IPv4
ipv4_num = 20
ipv6_num = 20
open_m3u_result = False
url_keywords_blacklist = epg.pw,skype.serv00.net,iptv.yjxfz.com,live-hls-web-ajb.getaj.net,live.goodiptv.club,hc73k3dhwo5gfkt.wcetv.com,stream1.freetv.fun,zw9999.cnstream.top,zsntlqj.xicp.net
    
open_subscribe = True


open_multicast = True
open_multicast_foodie = True
open_multicast_fofa = True
multicast_region_list = 全部
multicast_page_num = 1
open_proxy = False
open_driver = False
open_hotel = True
open_hotel_foodie = True
open_hotel_fofa = True
hotel_region_list = 全部
hotel_page_num = 1
open_update_time = False
request_timeout = 10
origin_type_prefer = hotel,multicast,subscribe,online_search
hotel_num = 20
multicast_num = 20
subscribe_num = 20
online_search_num = 20
open_url_info = False
open_empty_category = False
response_time_weight = 0.5`

**Comment by zhycn9033** [comment]
![Uploading QQ20241213-173158.png…]()

**Comment by zhycn9033** [comment]
![QQ20241213-173255](https://github.com/user-attachments/assets/ed174ca5-f023-4da6-b164-e7e393c9d602)
![QQ20241213-172750](https://github.com/user-attachments/assets/84a72c32-1cad-479e-b53d-ee839f8b901a)
![QQ20241213-173158](https://github.com/user-attachments/assets/5dbe4232-f8b1-4fee-b45e-47c61076ef86)

**Comment by zhycn9033** [comment]
![QQ20241213-174133](https://github.com/user-attachments/assets/8c68ab18-01c1-44eb-8b7f-cf36f40cf760)
