### ISSUE TITLE
【IPV6检测】测试IPV6的地址是否可以替换一个

### ISSUE THREAD

**Issue by 907739769** [Guovin/iptv-api#681]
### Don't skip these steps

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field
- [X] I have checked through the search that there are no similar issues that already exist
- [X] I will not submit any issues that are not related to this project

### Occurrence environment

- [ ] Workflow
- [ ] GUI
- [X] Docker
- [ ] Command line

### Bug description

    url = "https://ipv6.tokyo.test-ipv6.com/ip/?callback=?&testdomain=test-ipv6.com&testname=test_aaaa"
测试IPV6的地址是否可以替换   这个地址有丢包情况，我不确定是否是我的个例

def check_ipv6_support():
    """
    Check if the system network supports ipv6
    """
    url = "https://ipv6.tokyo.test-ipv6.com/ip/?callback=?&testdomain=test-ipv6.com&testname=test_aaaa"
    try:
        print("Checking if your network supports IPv6...")
        response = requests.get(url, timeout=10)
        if response.status_code == 200:
            print("Your network supports IPv6")
            return True
    except Exception:
        pass
    print("Your network does not support IPv6, don't worry, these results will be saved")
    return False

### Error log

```shell
Checking if your network supports IPv6...

Your network does not support IPv6
```

**Comment by 907739769** [comment]
或者能不能加个重试机制

**Comment by Guovin** [comment]
如果你确定你的网络支持ipv6，这个检测并不会影响最终结果是否含有ipv6，因为它只决定是否对ipv6的接口进行测速，如果你开启了保留ipv6结果，检测失败仍然会保留这些结果。偶尔的检测失败影响并不大，但添加重试会影响每次的更新，使更新时间延长。
