### ISSUE TITLE
询问demo文件的一些问题

### ISSUE THREAD

**Issue by Bearlele** [Guovin/iptv-api#684]
### Don't skip these steps

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field
- [X] I have checked through the search that there are no similar issues that already exist
- [X] I will not submit any issues that are not related to this project

### Occurrence environment

- [ ] Workflow
- [ ] GUI
- [X] Docker
- [ ] Command line

### Question description

请问demo这个文件手动编写的话他是如何匹配频道名的是模糊匹配还是精准匹配，假如我有以下源，demo文件内写“NHK”会把这些源都判定为同一个频道吗？
NHK新闻资讯台, mitv://generationnexxxt.com:19806/c2da55d84a72418c8f1876c25ec97a1d
NHK東京総合, http://aktv.top/AKTV/live/aktv3/nhk/AKTV.m3u8
NHK総合, https://nhk4.mov3.co/hls/nhk.m3u8

**Comment by Bearlele** [comment]
我注意到这个lssues(https://github.com/Guovin/iptv-api/issues/121)提到了有模糊匹配功能，请问有相应的文档表明该如何使用模糊匹配吗

**Comment by Guovin** [comment]
默认执行的就是模糊匹配，无需操作。你提到的这三个频道，会被识别为三种频道。目前只支持特殊符号和部分关键字的频道模糊匹配。

**Comment by Bearlele** [comment]
明白了谢谢，请问后期是否有考虑加入正则的匹配机制？

**Comment by Guovin** [comment]
> 明白了谢谢，请问后期是否有考虑加入正则的匹配机制？

后面会考虑增加匹配规则组，由于频道众多，每种频道的处理不尽相同，需要长期维护。
