### ISSUE TITLE
github代理地址不稳定

### ISSUE THREAD

**Issue by tianniao886** [Guovin/iptv-api#685]
### Don't skip these steps

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field
- [X] I have checked through the search that there are no similar issues that already exist
- [X] I will not submit any issues that are not related to this project

### Occurrence environment

- [ ] Workflow
- [ ] GUI
- [x] Docker
- [ ] Command line

### Question description

首先感谢作者的付出！！！期待项目越做越好！！
github代理地址不稳定，时好时坏...修改了hosts也不行。这样很多源无法访问。
群晖7.22 Docker 运行时，6:00\18:00定时自动更新任务失效。不会自动运行。

**Comment by Guovin** [comment]
1.代理地址是第三方提供的服务，国内一般都是可以访问的。
2.docker定时运行问题，请提供日志。

**Comment by Guovin** [comment]
提醒一下，能否定时执行，取决于查看结果文件的更新时间

**Comment by 907739769** [comment]
请求增加不属于代理的选项，太不稳定了，本来我的网络是可以访问github的，加上就访问不了
Failed to connect to the http://itv.22m.top/ITVBox/tv/tvonline.txt. Retrying 1...

Failed to connect to the https://ghp.ci/https://raw.githubusercontent.com/kimwang1978/collect-tv-txt/main/merged_output.txt. Retrying 1...

Failed to connect to the https://ghp.ci/https://raw.githubusercontent.com/joevess/IPTV/main/home.m3u8. Retrying 1...

Failed to connect to the https://ghp.ci//https://raw.githubusercontent.com/asdjkl6/tv/tv/.m3u/整套直播源/测试/整套直播源/kk.txt. Retrying 1...

Failed to connect to the https://ghp.ci//https://raw.githubusercontent.com/asdjkl6/tv/tv/.m3u/整套直播源/测试/整套直播源/l.txt. Retrying 1...

Failed to connect to the https://ghp.ci/https://raw.githubusercontent.com/xzw832/cmys/main/S_weishi.txt. Retrying 1...

Error on http://itv.22m.top/ITVBox/tv/tvonline.txt: Failed to connect to the http://itv.22m.top/ITVBox/tv/tvonline.txt reached the maximum retries.

Error on https://ghp.ci/https://raw.githubusercontent.com/joevess/IPTV/main/home.m3u8: Failed to connect to the https://ghp.ci/https://raw.githubusercontent.com/joevess/IPTV/main/home.m3u8 reached the maximum retries.

Error on https://ghp.ci//https://raw.githubusercontent.com/asdjkl6/tv/tv/.m3u/整套直播源/测试/整套直播源/kk.txt: Failed to connect to the https://ghp.ci//https://raw.githubusercontent.com/asdjkl6/tv/tv/.m3u/整套直播源/测试/整套直播源/kk.txt reached the maximum retries.

Error on https://ghp.ci//https://raw.githubusercontent.com/asdjkl6/tv/tv/.m3u/整套直播源/测试/整套直播源/l.txt: Failed to connect to the https://ghp.ci//https://raw.githubusercontent.com/asdjkl6/tv/tv/.m3u/整套直播源/测试/整套直播源/l.txt reached the maximum retries.

Error on https://ghp.ci/https://raw.githubusercontent.com/xzw832/cmys/main/S_weishi.txt: Failed to connect to the https://ghp.ci/https://raw.githubusercontent.com/xzw832/cmys/main/S_weishi.txt reached the maximum retries.

Error on https://ghp.ci/https://raw.githubusercontent.com/kimwang1978/collect-tv-txt/main/merged_output.txt: Failed to connect to the https://ghp.ci/https://raw.githubusercontent.com/kimwang1978/collect-tv-txt/main/merged_output.txt reached the maximum retries.

**Comment by 907739769** [comment]
https://ghp.ci/  这个地址用代理访问才行  多此一举啊，，

**Comment by Guovin** [comment]
> https://ghp.ci/ 这个地址用代理访问才行 多此一举啊，，

这属于订阅源地址，可以自行修改，新版v1.5.6已经移除ghp.ci，并以jsdelivr代替

**Comment by 907739769** [comment]
> > https://ghp.ci/ 这个地址用代理访问才行 多此一举啊，，
> 
> 这属于订阅源地址，可以自行修改，新版v1.5.6已经移除ghp.ci，并以jsdelivr代替；国内用户大多访问github是需要代理的，并不是多此一举，如果你不需要，可以修改config/subscribe.txt中的地址，移除其中的代理前缀。

我的意思是说要用代理访问ghp.ci才能正常访问到，不用代理访问不了ghp.ci，所以说多此一举了😂

**Comment by Guovin** [comment]
> > > https://ghp.ci/ 这个地址用代理访问才行 多此一举啊，，
> > 
> > 
> > 这属于订阅源地址，可以自行修改，新版v1.5.6已经移除ghp.ci，并以jsdelivr代替；国内用户大多访问github是需要代理的，并不是多此一举，如果你不需要，可以修改config/subscribe.txt中的地址，移除其中的代理前缀。
> 
> 我的意思是说要用代理访问ghp.ci才能正常访问到，不用代理访问不了ghp.ci，所以说多此一举了😂

并不是多此一举，代理ghp.ci访问不了是因为昨天开始这个代理挂了。如果不用代理，国内多数用户访问github是有困难的。还是我上面说的那样，如果你确保你的网络无需代理就可以访问，可以自行移除代理地址。

**Comment by 907739769** [comment]
> > > > https://ghp.ci/ 这个地址用代理访问才行 多此一举啊，，
> > > 
> > > 
> > > 这属于订阅源地址，可以自行修改，新版v1.5.6已经移除ghp.ci，并以jsdelivr代替；国内用户大多访问github是需要代理的，并不是多此一举，如果你不需要，可以修改config/subscribe.txt中的地址，移除其中的代理前缀。
> > 
> > 
> > 我的意思是说要用代理访问ghp.ci才能正常访问到，不用代理访问不了ghp.ci，所以说多此一举了😂
> 
> 并不是多此一举，代理ghp.ci访问不了是因为昨天开始这个代理挂了。如果不用代理，国内多数用户访问github是有困难的。还是我上面说的那样，如果你确保你的网络无需代理就可以访问，可以自行移除代理地址。

好的 感谢回复
