### ISSUE TITLE
内网源添加白名单

### ISSUE THREAD

**Issue by claudecaicai** [Guovin/iptv-api#688]
问题：环境docker lite版，我做了feiyang/allinone内网源，在/docker/iptv_api/config/config.ini内部给了参数subscribe_urls = http://192.168.1.5:35455/tv.m3u，然后输出/docker/iptv_api/output/result.m3u显示频道为空。
看到有类似问题，是去/docker/iptv_api/config/demo.txt添加白名单
CCTV源链接是这样的：http://192.168.1.5:35455/ysptp/cctv1.m3u8
测试白名单添加
CCTV-1,http://192.168.1.5$!
CCTV-2,http://192.168.1.5:35455/tv.m3u$!
CCTV-3,http://192.168.1.5:35455/itv/6000000001000022313.m3u8?cdn=wasusyt$!
CCTV-4,http://192.168.1.5:35455$!
输出的result.m3u还是为空
请问下大佬们到底咋添加

**Comment by zhycn9033** [comment]
open_use_old_result = True
需要打开这个，否则白名单不生效

**Comment by claudecaicai** [comment]
> open_use_old_result = True 需要打开这个，否则白名单不生效

这个参数是true的，开了的

**Comment by Guovin** [comment]
你这样做是正确的，应该是没问题的，提供下容器运行日志？

**Comment by claudecaicai** [comment]
> 你这样做是正确的，应该是没问题的，提供下容器运行日志？
日志如下

[_clever_mendel_logs.txt](https://github.com/user-attachments/files/18145761/_clever_mendel_logs.txt)
其中config文件如下，方便查看修改为了TXT
[config.txt](https://github.com/user-attachments/files/18145782/config.txt)

或直接这边查看
https://github.com/claudecaicai/iptv-api/tree/master/TEST-iptv_api

**Comment by Guovin** [comment]
> > 你这样做是正确的，应该是没问题的，提供下容器运行日志？
> > 日志如下
> 
> [_clever_mendel_logs.txt](https://github.com/user-attachments/files/18145761/_clever_mendel_logs.txt) 其中config文件如下，方便查看修改为了TXT [config.txt](https://github.com/user-attachments/files/18145782/config.txt)
> 
> 或直接这边查看 https://github.com/claudecaicai/iptv-api/tree/master/TEST-iptv_api

日志显示没有获取到更新数据，你的订阅源只有一个，有可能是请求失败导致，建议检查网络原因。刚刚v1.5.6已经更新，更新最新镜像再试试。

**Comment by claudecaicai** [comment]
> > > 你这样做是正确的，应该是没问题的，提供下容器运行日志？
> > > 日志如下
> > 
> > 
> > [_clever_mendel_logs.txt](https://github.com/user-attachments/files/18145761/_clever_mendel_logs.txt) 其中config文件如下，方便查看修改为了TXT [config.txt](https://github.com/user-attachments/files/18145782/config.txt)
> > 或直接这边查看 https://github.com/claudecaicai/iptv-api/tree/master/TEST-iptv_api
> 
> 日志显示没有获取到更新数据，你的订阅源只有一个，有可能是请求失败导致，建议检查网络原因。刚刚v1.5.6已经更新，更新最新镜像再试试。

感谢Guovin，更新新的镜像后，在dome添加的白名单源在output/result.m3u有对应输出，同时http://IP:8000/m3u放在播放器源可用（CCTV3可播放）
#EXTM3U x-tvg-url="https://live.fanmingming.com/e.xml"
#EXTINF:-1 tvg-name="2024-12-17 12:58:07" tvg-logo="https://live.fanmingming.com/tv/2024-12-17 12:58:07.png" group-title="更新时间",2024-12-17 12:58:07
url
#EXTINF:-1 tvg-name="CCTV1" tvg-logo="https://live.fanmingming.com/tv/CCTV1.png" group-title="📺央视频道",CCTV-1
http://192.168.1.5
#EXTINF:-1 tvg-name="CCTV2" tvg-logo="https://live.fanmingming.com/tv/CCTV2.png" group-title="📺央视频道",CCTV-2
http://192.168.1.5:35455/tv.m3u
#EXTINF:-1 tvg-name="CCTV3" tvg-logo="https://live.fanmingming.com/tv/CCTV3.png" group-title="📺央视频道",CCTV-3
http://192.168.1.5:35455/itv/6000000001000022313.m3u8?cdn=wasusyt
#EXTINF:-1 tvg-name="CCTV4" tvg-logo="https://live.fanmingming.com/tv/CCTV4.png" group-title="📺央视频道",CCTV-4
http://192.168.1.5:35455

但是其他内网源仍然无法别读出，日志显示没有获取到更新数据，跟换其他源都可以获取到更新数据（/config/subscribe.txt下其他源）
日志链接：
https://raw.githubusercontent.com/claudecaicai/iptv-api/refs/heads/master/TEST-iptv_api/_clever_mendel_logs.txt

我在/config/subscribe.txt添加了内网源

# 这是订阅源列表，每行一个订阅地址
# This is a list of subscription sources, with one subscription address per line
# https://iptv.b2og.com/txt/fmml_ipv6.txt
# # https://cdn.jsdelivr.net/gh/suxuang/myIPTV@main/ipv6.m3u
# https://live.zbds.top/tv/iptv6.txt
# https://live.zbds.top/tv/iptv4.txt
# https://live.fanmingming.com/tv/m3u/ipv6.m3u
# https://cdn.jsdelivr.net/gh/joevess/IPTV@main/home.m3u8
# https://aktv.top/live.txt
# http://175.178.251.183:6689/live.txt
# https://cdn.jsdelivr.net/gh/kimwang1978/collect-tv-txt@main/merged_output.txt
# https://m3u.ibert.me/txt/fmml_dv6.txt
# https://m3u.ibert.me/txt/o_cn.txt
# https://m3u.ibert.me/txt/j_iptv.txt
# https://cdn.jsdelivr.net/gh/xzw832/cmys@main/S_CCTV.txt
# https://cdn.jsdelivr.net/gh/xzw832/cmys@main/S_weishi.txt
# https://cdn.jsdelivr.net/gh/asdjkl6/tv@tv/.m3u/整套直播源/测试/整套直播源/l.txt
# https://cdn.jsdelivr.net/gh/asdjkl6/tv@tv/.m3u/整套直播源/测试/整套直播源/kk.txt
http://192.168.1.5:35455/tv.m3u

麻烦大佬请问是否可以测试下youshandefeiyang/allinone项目的本地源是否可以获取到更新数据
docker run -d --name watchtower --restart=always -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower allinone  --cleanup --interval 3600
源链接：http://IP:35455/tv.m3u
万分感谢

**Comment by Guovin** [comment]
@claudecaicai 我尝试运行了你说的这个镜像，但无日志输出，且无法访问

**Comment by w1365258** [comment]
你的35455端口未开放，无法访问。最直接的方法就是添加docker容器时直接映射到根目录的www下面，不用开端口号就可以访问了
