### ISSUE TITLE
关于Docker配置问题？

### ISSUE THREAD

**Issue by fanghg2018** [Guovin/iptv-api#689]
### Don't skip these steps

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field
- [X] I have checked through the search that there are no similar issues that already exist
- [X] I will not submit any issues that are not related to this project

### Occurrence environment

- [ ] Workflow
- [ ] GUI
- [X] Docker
- [ ] Command line

### Question description

我在群晖上用docker部署了项目，配置里设了 min_resolution = 1920x1080，为什么还有很多720X576的片源，另外，里面没有最小速度配置项是怎么回事。

**Comment by fanghg2018** [comment]
docker的config.ini里没有
min_speed | 接口最小速率（单位M/s），
 open_filter_speed 
这两个配置项

**Comment by Guovin** [comment]
新版移除了ffmpeg，暂时无法过滤分辨率；速率过滤属于内测功能，docker镜像暂未更新
