### ISSUE TITLE
关于提供可设置的更新频率及更新时间功能请求

### ISSUE THREAD

**Issue by raynlong** [Guovin/iptv-api#690]
### Don't skip these steps

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field
- [X] I have checked through the search that there are no similar issues that already exist
- [X] I will not submit any issues that are not related to this project

### Application environment

- [ ] Workflow
- [ ] GUI
- [X] Docker
- [ ] Command line

### Enhancement description

希望在config.ini文件中增加更新频率的控制设置，比如每5天一次更新，在当天的早上6点。因为iptv源的稳定性不需要每天更新2次。赞美作者！

### Related log

```shell
暂无
```

**Comment by Guovin** [comment]
#440 重复
