### ISSUE TITLE
没有ipv6源了吗

### ISSUE THREAD

**Issue by 907739769** [Guovin/iptv-api#697]
### Don't skip these steps

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field
- [X] I have checked through the search that there are no similar issues that already exist
- [X] I will not submit any issues that are not related to this project

### Occurrence environment

- [ ] Workflow
- [ ] GUI
- [X] Docker
- [ ] Command line

### Bug description

生成的都是ipv4  ，单独设置的ipv6生成结果是空的
更新时间,#genre#
2024-12-17 13:24:28,url
📺央视频道,#genre#
CCTV-1,http://221.233.192.152:1111/tsfile/live/0001_1.m3u8?key=txiptv&playlive=1&authid=0$湖北酒店源
CCTV-1,http://183.94.146.109:2222/tsfile/live/0001_1.m3u8?key=txiptv&playlive=1&authid=0$湖北酒店源
CCTV-1,http://221.222.162.206:8888/rtp/239.3.1.129:8008$组播源
CCTV-1,http://221.219.79.161:4000/rtp/239.3.1.129:8008$组播源
CCTV-1,http://www.furymax.top:85/rtp/239.254.96.96:8550$组播源
CCTV-1,http://124.231.215.118:9999/tsfile/live/0001_1.m3u8$订阅源
CCTV-1,http://123.52.110.137:9901/tsfile/live/0001_1.m3u8$订阅源
CCTV-1,http://163.177.122.21:9901/tsfile/live/1019_1.m3u8$订阅源
CCTV-2,http://221.233.192.152:1111/tsfile/live/0002_1.m3u8?key=txiptv&playlive=1&authid=0$湖北酒店源
CCTV-2,http://183.94.146.109:2222/tsfile/live/0002_1.m3u8?key=txiptv&playlive=1&authid=0$湖北酒店源
CCTV-2,http://123.113.187.204:8000/rtp/239.3.1.60:8084$组播源
CCTV-2,http://221.222.162.206:8888/rtp/239.3.1.60:8084$组播源
CCTV-2,http://221.219.79.161:4000/rtp/239.3.1.60:8084$组播源
CCTV-2,http://124.231.215.118:9999/tsfile/live/0002_1.m3u8$订阅源
CCTV-2,http://123.52.110.137:9901/tsfile/live/0002_1.m3u8$订阅源
CCTV-2,http://163.177.122.21:9901/tsfile/live/1020_1.m3u8$订阅源
CCTV-3,http://221.233.192.152:1111/tsfile/live/0003_1.m3u8?key=txiptv&playlive=1&authid=0$湖北酒店源
CCTV-3,http://183.94.146.109:2222/tsfile/live/0003_1.m3u8?key=txiptv&playlive=1&authid=0$湖北酒店源
CCTV-3,http://123.113.187.204:8000/rtp/239.3.1.172:8001$组播源
CCTV-3,http://221.222.162.206:8888/rtp/239.3.1.172:8001$组播源
CCTV-3,http://221.219.79.161:4000/rtp/239.3.1.172:8001$组播源

只要ipv6就是空的
📺央视频道,#genre#

📡卫视频道,#genre#

### Error log

```shell
Starting periodic command scheduler: cron.

[2024-12-17 13:52:51 +0800] [17] [INFO] Starting gunicorn 23.0.0

[2024-12-17 13:52:51 +0800] [17] [INFO] Listening at: http://0.0.0.0:8000 (17)

[2024-12-17 13:52:51 +0800] [17] [INFO] Using worker: sync

[2024-12-17 13:52:51 +0800] [24] [INFO] Booting worker with pid: 24


Processing subscribe :   0%|          | 0/16 [00:00<?, ?it/s]
Processing subscribe :   6%|▋         | 1/16 [00:05<01:15,  5.04s/it]
Processing subscribe :  12%|█▎        | 2/16 [00:05<00:34,  2.50s/it]
Processing subscribe :  19%|█▉        | 3/16 [00:08<00:35,  2.71s/it]
Processing subscribe :  25%|██▌       | 4/16 [00:14<00:44,  3.73s/it]
Processing subscribe :  31%|███▏      | 5/16 [00:14<00:27,  2.49s/it]
Processing subscribe :  38%|███▊      | 6/16 [00:14<00:17,  1.74s/it]
Processing subscribe :  44%|████▍     | 7/16 [00:26<00:44,  4.95s/it]
Processing subscribe :  50%|█████     | 8/16 [00:38<00:57,  7.22s/it]
Processing subscribe :  56%|█████▋    | 9/16 [00:40<00:40,  5.76s/it]
Processing subscribe :  62%|██████▎   | 10/16 [00:41<00:25,  4.22s/it]
Processing subscribe :  69%|██████▉   | 11/16 [00:43<00:17,  3.59s/it]
Processing subscribe :  75%|███████▌  | 12/16 [00:46<00:12,  3.20s/it]
Processing subscribe :  81%|████████▏ | 13/16 [00:46<00:07,  2.42s/it]
Processing subscribe :  88%|████████▊ | 14/16 [01:16<00:21, 10.73s/it]
Processing subscribe :  94%|█████████▍| 15/16 [01:32<00:12, 12.38s/it]
Processing subscribe : 100%|██████████| 16/16 [02:59<00:00, 34.74s/it]
Processing subscribe : 100%|██████████| 16/16 [02:59<00:00, 11.22s/it]

Failed to connect to the https://live.fanmingming.com/tv/m3u/ipv6.m3u. Retrying 1...

Failed to connect to the https://aktv.top/live.txt. Retrying 1...

Error on https://aktv.top/live.txt: Failed to connect to the https://aktv.top/live.txt reached the maximum retries.

CCTV-1: History: 162, Hotel_fofa: 27, Multicast: 0, Hotel_foodie: 77, Subscribe: 334, total: 63

CCTV-2: History: 167, Hotel_fofa: 28, Multicast: 0, Hotel_foodie: 82, Subscribe: 310, total: 42

CCTV-3: History: 157, Hotel_fofa: 26, Multicast: 0, Hotel_foodie: 81, Subscribe: 303, total: 40

CCTV-4: History: 197, Hotel_fofa: 26, Multicast: 0, Hotel_foodie: 86, Subscribe: 357, total: 44

CCTV-5: History: 158, Hotel_fofa: 28, Multicast: 0, Hotel_foodie: 81, Subscribe: 321, total: 56

CCTV-5+: History: 104, Hotel_fofa: 18, Multicast: 0, Hotel_foodie: 64, Subscribe: 220, total: 42

CCTV-6: History: 167, Hotel_fofa: 28, Multicast: 0, Hotel_foodie: 79, Subscribe: 303, total: 43

CCTV-7: History: 165, Hotel_fofa: 26, Multicast: 0, Hotel_foodie: 62, Subscribe: 312, total: 50

CCTV-8: History: 161, Hotel_fofa: 27, Multicast: 0, Hotel_foodie: 81, Subscribe: 291, total: 38

CCTV-9: History: 159, Hotel_fofa: 28, Multicast: 0, Hotel_foodie: 81, Subscribe: 307, total: 54

CCTV-10: History: 159, Hotel_fofa: 26, Multicast: 0, Hotel_foodie: 83, Subscribe: 313, total: 51

CCTV-11: History: 149, Hotel_fofa: 27, Multicast: 0, Hotel_foodie: 80, Subscribe: 284, total: 41

CCTV-12: History: 155, Hotel_fofa: 28, Multicast: 0, Hotel_foodie: 81, Subscribe: 318, total: 55

CCTV-13: History: 149, Hotel_fofa: 28, Multicast: 0, Hotel_foodie: 80, Subscribe: 285, total: 43

CCTV-14: History: 147, Hotel_fofa: 28, Multicast: 0, Hotel_foodie: 75, Subscribe: 316, total: 51

CCTV-15: History: 147, Hotel_fofa: 27, Multicast: 0, Hotel_foodie: 77, Subscribe: 288, total: 41

CCTV-16: History: 80, Hotel_fofa: 1, Multicast: 0, Hotel_foodie: 13, Subscribe: 166, total: 35

CCTV-17: History: 91, Hotel_fofa: 7, Multicast: 0, Hotel_foodie: 49, Subscribe: 212, total: 47

广东卫视: History: 137, Hotel_fofa: 22, Multicast: 148, Hotel_foodie: 87, Subscribe: 302, total: 72

香港卫视: History: 5, Hotel_fofa: 0, Multicast: 0, Hotel_foodie: 4, Subscribe: 11, total: 0

浙江卫视: History: 140, Hotel_fofa: 26, Multicast: 146, Hotel_foodie: 88, Subscribe: 314, total: 84

湖南卫视: History: 148, Hotel_fofa: 26, Multicast: 148, Hotel_foodie: 91, Subscribe: 277, total: 44

北京卫视: History: 143, Hotel_fofa: 25, Multicast: 138, Hotel_foodie: 89, Subscribe: 279, total: 44

湖北卫视: History: 137, Hotel_fofa: 23, Multicast: 153, Hotel_foodie: 88, Subscribe: 265, total: 43

黑龙江卫视: History: 120, Hotel_fofa: 14, Multicast: 146, Hotel_foodie: 84, Subscribe: 245, total: 44

安徽卫视: History: 137, Hotel_fofa: 26, Multicast: 138, Hotel_foodie: 83, Subscribe: 257, total: 43

重庆卫视: History: 133, Hotel_fofa: 16, Multicast: 136, Hotel_foodie: 81, Subscribe: 247, total: 43

东方卫视: History: 145, Hotel_fofa: 25, Multicast: 132, Hotel_foodie: 71, Subscribe: 280, total: 48

东南卫视: History: 109, Hotel_fofa: 21, Multicast: 133, Hotel_foodie: 82, Subscribe: 232, total: 44

甘肃卫视: History: 82, Hotel_fofa: 7, Multicast: 71, Hotel_foodie: 54, Subscribe: 170, total: 41

广西卫视: History: 121, Hotel_fofa: 16, Multicast: 112, Hotel_foodie: 71, Subscribe: 227, total: 44

贵州卫视: History: 131, Hotel_fofa: 19, Multicast: 138, Hotel_foodie: 81, Subscribe: 251, total: 45

海南卫视: History: 63, Hotel_fofa: 9, Multicast: 118, Hotel_foodie: 41, Subscribe: 170, total: 44

河北卫视: History: 130, Hotel_fofa: 16, Multicast: 138, Hotel_foodie: 80, Subscribe: 239, total: 45

河南卫视: History: 133, Hotel_fofa: 15, Multicast: 138, Hotel_foodie: 81, Subscribe: 237, total: 43

吉林卫视: History: 118, Hotel_fofa: 16, Multicast: 118, Hotel_foodie: 83, Subscribe: 219, total: 44

江苏卫视: History: 149, Hotel_fofa: 25, Multicast: 148, Hotel_foodie: 92, Subscribe: 287, total: 48

江西卫视: History: 123, Hotel_fofa: 20, Multicast: 138, Hotel_foodie: 86, Subscribe: 238, total: 42

辽宁卫视: History: 128, Hotel_fofa: 20, Multicast: 156, Hotel_foodie: 78, Subscribe: 250, total: 45

内蒙古卫视: History: 71, Hotel_fofa: 5, Multicast: 51, Hotel_foodie: 71, Subscribe: 153, total: 24

宁夏卫视: History: 88, Hotel_fofa: 9, Multicast: 57, Hotel_foodie: 73, Subscribe: 170, total: 32

青海卫视: History: 78, Hotel_fofa: 9, Multicast: 70, Hotel_foodie: 71, Subscribe: 180, total: 36

山东卫视: History: 126, Hotel_fofa: 22, Multicast: 148, Hotel_foodie: 87, Subscribe: 246, total: 45

山西卫视: History: 96, Hotel_fofa: 12, Multicast: 62, Hotel_foodie: 70, Subscribe: 150, total: 21

陕西卫视: History: 94, Hotel_fofa: 12, Multicast: 65, Hotel_foodie: 76, Subscribe: 160, total: 20

四川卫视: History: 135, Hotel_fofa: 16, Multicast: 149, Hotel_foodie: 84, Subscribe: 249, total: 44

深圳卫视: History: 137, Hotel_fofa: 25, Multicast: 148, Hotel_foodie: 83, Subscribe: 279, total: 55

三沙卫视: History: 40, Hotel_fofa: 2, Multicast: 41, Hotel_foodie: 11, Subscribe: 79, total: 10

天津卫视: History: 143, Hotel_fofa: 21, Multicast: 148, Hotel_foodie: 87, Subscribe: 271, total: 45

西藏卫视: History: 69, Hotel_fofa: 7, Multicast: 62, Hotel_foodie: 63, Subscribe: 152, total: 24

新疆卫视: History: 56, Hotel_fofa: 7, Multicast: 57, Hotel_foodie: 66, Subscribe: 135, total: 34

云南卫视: History: 101, Hotel_fofa: 11, Multicast: 98, Hotel_foodie: 81, Subscribe: 198, total: 41

Checking if your network supports IPv6...

Your network supports IPv6

Total urls: 2215, need to sort: 103


Sorting:   0%|          | 0/103 [00:00<?, ?it/s]
Sorting:  99%|█████████▉| 102/103 [00:01<00:00, 83.67it/s]


Writing: 0it [00:00, ?it/s]
Sorting: 100%|██████████| 103/103 [00:10<00:00,  9.63it/s]


Writing: 0it [00:00, ?it/s]

📺央视频道: CCTV-1: 0, CCTV-2: 0, CCTV-3: 0, CCTV-4: 0, CCTV-5: 0, CCTV-5+: 0, CCTV-6: 0, CCTV-7: 0, CCTV-8: 0, CCTV-9: 0, CCTV-10: 0, CCTV-11: 0, CCTV-12: 0, CCTV-13: 0, CCTV-14: 0, CCTV-15: 0, CCTV-16: 0, CCTV-17: 0

📡卫视频道: 广东卫视: 0, 香港卫视: 0, 浙江卫视: 0, 湖南卫视: 0, 北京卫视: 0, 湖北卫视: 0, 黑龙江卫视: 0, 安徽卫视: 0, 重庆卫视: 0, 东方卫视: 0, 东南卫视: 0, 甘肃卫视: 0, 广西卫视: 0, 贵州卫视: 0, 海南卫视: 0, 河北卫视: 0, 河南卫视: 0, 吉林卫视: 0, 江苏卫视: 0, 江西卫视: 0, 辽宁卫视: 0, 内蒙古卫视: 0, 宁夏卫视: 0, 青海卫视: 0, 山东卫视: 0, 山西卫视: 0, 陕西卫视: 0, 四川卫视: 0, 深圳卫视: 0, 三沙卫视: 0, 天津卫视: 0, 西藏卫视: 0, 新疆卫视: 0, 云南卫视: 0

✅ M3U result file generated at: /iptv-api/output/result.m3u

🥳 Update completed! Total time spent: 03:15. Please check the output/result.txt file!
```

**Comment by 907739769** [comment]
Name: CCTV-1, URL: http://[2409:8087:5e00:24::11]:6060/200000001898/460000089800010144/$订阅源, Date: None, Delay: 1189 ms, Speed: 0.00 M/s, Resolution: None
Name: CCTV-1, URL: http://[2409:8087:5e00:24::10]:6060/200000001898/460000089800010144/$订阅源, Date: None, Delay: None ms, Speed: 0.00 M/s, Resolution: None
Name: CCTV-2, URL: http://[2409:8087:5e00:24::11]:6060/200000001898/460000089800010211/$订阅源, Date: None, Delay: 1189 ms, Speed: 0.00 M/s, Resolution: None
Name: CCTV-3, URL: http://[2409:8087:5e00:24::11]:6060/200000001898/460000089800010212/$订阅源, Date: None, Delay: 1189 ms, Speed: 0.00 M/s, Resolution: None
Name: CCTV-5, URL: http://[2409:8087:5e00:24::11]:6060/200000001898/460000089800010145/$订阅源, Date: None, Delay: 1189 ms, Speed: 0.00 M/s, Resolution: None
Name: CCTV-5, URL: http://[2409:8087:5e00:24::10]:6060/200000001898/460000089800010139/$订阅源, Date: None, Delay: None ms, Speed: 0.00 M/s, Resolution: None
Name: CCTV-5, URL: http://[2409:8087:5e00:24::11]:6060/200000001898/460000089800010139/$订阅源, Date: None, Delay: 1189 ms, Speed: 0.00 M/s, Resolution: None
Name: CCTV-5+, URL: http://[2409:8087:5e00:24::10]:6060/200000001898/460000089800010202/$订阅源, Date: None, Delay: None ms, Speed: 0.00 M/s, Resolution: None
Name: CCTV-6, URL: http://[2409:8087:5e00:24::11]:6060/200000001898/460000089800010214/$订阅源, Date: None, Delay: 1189 ms, Speed: 0.00 M/s, Resolution: None
Name: CCTV-7, URL: http://[2409:8087:5e00:24::10]:6060/200000001898/460000089800010215/$订阅源, Date: None, Delay: None ms, Speed: 0.00 M/s, Resolution: None
Name: CCTV-7, URL: http://[2409:8087:5e00:24::11]:6060/200000001898/460000089800010215/$订阅源, Date: None, Delay: 1189 ms, Speed: 0.00 M/s, Resolution: None
Name: CCTV-8, URL: http://[2409:8087:5e00:24::11]:6060/200000001898/460000089800010216/$订阅源, Date: None, Delay: 1189 ms, Speed: 0.00 M/s, Resolution: None
Name: CCTV-8, URL: http://[2409:8087:5e00:24::10]:6060/200000001898/460000089800010216/$订阅源, Date: None, Delay: None ms, Speed: 0.00 M/s, Resolution: None
Name: CCTV-9, URL: http://[2409:8087:5e00:24::11]:6060/200000001898/460000089800010217/$订阅源, Date: None, Delay: 1189 ms, Speed: 0.00 M/s, Resolution: None
Name: CCTV-9, URL: http://[2409:8087:5e00:24::10]:6060/200000001898/460000089800010052/$订阅源, Date: None, Delay: None ms, Speed: 0.00 M/s, Resolution: None
Name: CCTV-9, URL: http://[2409:8087:5e00:24::10]:6060/200000001898/460000089800010217/$订阅源, Date: None, Delay: None ms, Speed: 0.00 M/s, Resolution: None
Name: CCTV-9, URL: http://[2409:8087:5e00:24::11]:6060/200000001898/460000089800010052/$订阅源, Date: None, Delay: 1189 ms, Speed: 0.00 M/s, Resolution: None
Name: CCTV-10, URL: http://[2409:8087:5e00:24::11]:6060/200000001898/460000089800010203/$订阅源, Date: None, Delay: 1189 ms, Speed: 0.00 M/s, Resolution: None
Name: CCTV-12, URL: http://[2409:8087:5e00:24::10]:6060/200000001898/460000089800010205/$订阅源, Date: None, Delay: None ms, Speed: 0.00 M/s, Resolution: None
Name: CCTV-12, URL: http://[2409:8087:5e00:24::11]:6060/200000001898/460000089800010205/$订阅源, Date: None, Delay: 1189 ms, Speed: 0.00 M/s, Resolution: None
Name: CCTV-14, URL: http://[2409:8087:5e00:24::11]:6060/200000001898/460000089800010207/$订阅源, Date: None, Delay: 1189 ms, Speed: 0.00 M/s, Resolution: None
Name: CCTV-16, URL: http://[2409:8087:5e00:24::11]:6060/200000001898/460000089800010142/$订阅源, Date: None, Delay: 1189 ms, Speed: 0.00 M/s, Resolution: None
Name: CCTV-16, URL: http://[2409:8087:5e00:24::10]:6060/200000001898/460000089800010142/$订阅源, Date: None, Delay: None ms, Speed: 0.00 M/s, Resolution: None
Name: CCTV-17, URL: http://[2409:8087:5e00:24::10]:6060/200000001898/460000089800010210/$订阅源, Date: None, Delay: None ms, Speed: 0.00 M/s, Resolution: None
Name: CCTV-17, URL: http://[2409:8087:5e00:24::11]:6060/200000001898/460000089800010210/$订阅源, Date: None, Delay: 1189 ms, Speed: 0.00 M/s, Resolution: None
Name: 湖南卫视, URL: http://[2409:8087:5e00:24::11]:6060/200000001898/460000089800010224/$订阅源, Date: None, Delay: 1189 ms, Speed: 0.00 M/s, Resolution: None
Name: 重庆卫视, URL: http://[2409:8087:5e00:24::11]:6060/200000001898/460000089800010053/$订阅源, Date: None, Delay: 1189 ms, Speed: 0.00 M/s, Resolution: None
Name: 东方卫视, URL: http://[2409:8087:5e00:24::10]:6060/200000001898/460000089800010054/$订阅源, Date: None, Delay: None ms, Speed: 0.00 M/s, Resolution: None
Name: 东方卫视, URL: http://[2409:8087:5e00:24::10]:6060/200000001898/460000089800010219/$订阅源, Date: None, Delay: None ms, Speed: 0.00 M/s, Resolution: None
Name: 甘肃卫视, URL: http://[2409:8087:5e00:24::11]:6060/200000001898/460000089800010098/1.m3u8$订阅源, Date: None, Delay: 1189 ms, Speed: 0.00 M/s, Resolution: None
Name: 江苏卫视, URL: http://[2409:8087:5e00:24::11]:6060/200000001898/460000089800010059/$订阅源, Date: None, Delay: 1189 ms, Speed: 0.00 M/s, Resolution: None
Name: 辽宁卫视, URL: http://[2409:8087:5e00:24::11]:6060/200000001898/460000089800010061/$订阅源, Date: None, Delay: 1189 ms, Speed: 0.00 M/s, Resolution: None
Name: 辽宁卫视, URL: http://[2409:8087:5e00:24::10]:6060/200000001898/460000089800010061/$订阅源, Date: None, Delay: None ms, Speed: 0.00 M/s, Resolution: None
Name: 山东卫视, URL: http://[2409:8087:5e00:24::10]:6060/200000001898/460000089800010066/$订阅源, Date: None, Delay: None ms, Speed: 0.00 M/s, Resolution: None
Name: 天津卫视, URL: http://[2409:8087:5e00:24::11]:6060/200000001898/460000089800010069/$订阅源, Date: None, Delay: 1189 ms, Speed: 0.00 M/s, Resolution: None

**Comment by 907739769** [comment]
[Settings]
open_driver = True
open_empty_category = False
open_filter_resolution = True
open_filter_speed = True
open_hotel = True
open_hotel_foodie = True
open_hotel_fofa = True
open_keep_all = False
open_m3u_result = True
open_multicast = True
open_multicast_foodie = True
open_multicast_fofa = True
open_online_search = False
open_proxy = False
open_request = False
open_service = True
open_sort = True
open_subscribe = True
open_update = True
open_update_time = False
open_url_info = True
open_use_cache = True
open_use_old_result = True
final_file = output/result.txt
hotel_num = 4
hotel_page_num = 1
hotel_region_list = 全部
ipv4_num = 5
ipv6_num = 5
ipv6_support = False
ipv_type = ipv6
ipv_type_prefer = IPv6
min_resolution = 1920x1080
min_speed = 0.2
multicast_num = 3
multicast_page_num = 1
multicast_region_list = 全部
online_search_num = 0
online_search_page_num = 1
origin_type_prefer = hotel,multicast,subscribe,online_search
recent_days = 30
request_timeout = 10
sort_timeout = 10
source_file = config/demo.txt
subscribe_num = 3
urls_limit = 1

**Comment by alantang1977** [comment]
感觉更新后获取的源不准确了，有些源秒播但一个都没获取到

**Comment by Guovin** [comment]
我用你一样的配置和默认订阅运行，是有ipv6输出的

**Comment by Guovin** [comment]
根据你的测速日志，你可以修改配置min_speed = 0试试

**Comment by Guovin** [comment]
> 感觉更新后获取的源不准确了，有些源秒播但一个都没获取到

例如？能给出具体地址吗？

**Comment by alantang1977** [comment]
https://www.mytvsuper.com.mp/m3u/Live.m3u
https://ghp.ci/https://raw.githubusercontent.com/alantang1977/X/live/live/myiptv.txt
这些好多台的源都获取不出来，是不是不支持

**Comment by Guovin** [comment]
> https://www.mytvsuper.com.mp/m3u/Live.m3u
> https://ghp.ci/https://raw.githubusercontent.com/alantang1977/X/live/live/myiptv.txt

我试了，是可以获取的，第二个地址代理已经挂了，要把https://ghp.ci/前缀移除

**Comment by alantang1977** [comment]
OK，我再试试，感谢！

**Comment by 907739769** [comment]
> 根据你的测速日志，你可以修改配置min_speed = 0试试

更改成0可以了，测试速度很慢  ，播放没啥问题

**Comment by riaiyuu** [comment]
> > https://www.mytvsuper.com.mp/m3u/Live.m3u
> > https://ghp.ci/https://raw.githubusercontent.com/alantang1977/X/live/live/myiptv.txt
> 
> 我试了，是可以获取的，第二个地址代理已经挂了，要把[https://ghp.ci/前缀移除](https://ghp.ci/%E5%89%8D%E7%BC%80%E7%A7%BB%E9%99%A4)

可以增加一项自定义代理的功能来获取播放源么，最近的github加速貌似都挂了，proxy功能打开日志也显示连接失败，

**Comment by Guovin** [comment]
> > > https://www.mytvsuper.com.mp/m3u/Live.m3u
> > > https://ghp.ci/https://raw.githubusercontent.com/alantang1977/X/live/live/myiptv.txt
> > 
> > 
> > 我试了，是可以获取的，第二个地址代理已经挂了，要把[https://ghp.ci/前缀移除](https://ghp.ci/%E5%89%8D%E7%BC%80%E7%A7%BB%E9%99%A4)
> 
> 可以增加一项自定义代理的功能来获取播放源么，最近的github加速貌似都挂了，proxy功能打开日志也显示连接失败，

每种代理的使用方式都不一样，无法提供多选，只能自行修改config/subscribe.txt文件

**Comment by Zhuazizizi** [comment]
我这也差不多情况，ipv6的地址测速结果不准确，基本都是0.1-0.3M/s左右，但实际访问看的话速度是正常的

**Comment by Guovin** [comment]
> 我这也差不多情况，ipv6的地址测速结果不准确，基本都是0.1-0.3M/s左右，但实际访问看的话速度是正常的

测速日志的ipv6是有显示速率的吗？没有像上面这样都是0吧？

**Comment by riaiyuu** [comment]
> > > > https://www.mytvsuper.com.mp/m3u/Live.m3u
> > > > https://ghp.ci/https://raw.githubusercontent.com/alantang1977/X/live/live/myiptv.txt
> > > 
> > > 
> > > 我试了，是可以获取的，第二个地址代理已经挂了，要把[https://ghp.ci/前缀移除](https://ghp.ci/%E5%89%8D%E7%BC%80%E7%A7%BB%E9%99%A4)
> > 
> > 
> > 可以增加一项自定义代理的功能来获取播放源么，最近的github加速貌似都挂了，proxy功能打开日志也显示连接失败，
> 
> 每种代理的使用方式都不一样，无法提供多选，只能自行修改config/subscribe.txt文件

不好意思，我的表达可能有些错误。我的意思是可不可以在获取源的时候，使用自己的代理服务器，测速筛选的时候直连。

虽然您在config里面内置了代理，但是我打开之后依然不能访问外网获取源，尤其是raw.githubusercontent。

我在容器的环境变量添加http_proxy和https_proxy之后，虽然能连接到外网获取直播源，但是筛选也时走的代理，可能会对结果产生负面影响。

**Comment by Guovin** [comment]
> > > > > https://www.mytvsuper.com.mp/m3u/Live.m3u
> > > > > https://ghp.ci/https://raw.githubusercontent.com/alantang1977/X/live/live/myiptv.txt
> > > > 
> > > > 
> > > > 我试了，是可以获取的，第二个地址代理已经挂了，要把[https://ghp.ci/前缀移除](https://ghp.ci/%E5%89%8D%E7%BC%80%E7%A7%BB%E9%99%A4)
> > > 
> > > 
> > > 可以增加一项自定义代理的功能来获取播放源么，最近的github加速貌似都挂了，proxy功能打开日志也显示连接失败，
> > 
> > 
> > 每种代理的使用方式都不一样，无法提供多选，只能自行修改config/subscribe.txt文件
> 
> 不好意思，我的表达可能有些错误。我的意思是可不可以在获取源的时候，使用自己的代理服务器，测速筛选的时候直连。
> 
> 虽然您在config里面内置了代理，但是我打开之后依然不能访问外网获取源，尤其是raw.githubusercontent。
> 
> 我在容器的环境变量添加http_proxy和https_proxy之后，虽然能连接到外网获取直播源，但是筛选也时走的代理，可能会对结果产生负面影响。

测速筛选阶段只有在对ipv6的接口使用代理，而且需要满足网络不支持ipv6的情况下，其余情况都是使用主机网络

**Comment by Zhuazizizi** [comment]
> > 我这也差不多情况，ipv6的地址测速结果不准确，基本都是0.1-0.3M/s左右，但实际访问看的话速度是正常的
> 
> 测速日志的ipv6是有显示速率的吗？没有像上面这样都是0吧？

速率有可能出现0，试了几次大概都是统一的速率像0.01或0这样，v4地址的测速正常。
```
Name: 湖南卫视, URL: http://[2409:8087:5e00:24::1e]:6060/200000001898/460000089800010224/$订阅源, Date: None, Delay: 188 ms, Speed: 0.01 M/s, Resolution: None
Name: 湖南卫视, URL: http://[2409:8087:5e00:24::1e]:6060/200000001898/460000089800010058/1.m3u8$订阅源, Date: None, Delay: 188 ms, Speed: 0.01 M/s, Resolution: None
Name: 湖南卫视, URL: http://[2409:8087:5e00:24::1e]:6060/200000001898/460000089800010058/index.m3u8$订阅源, Date: None, Delay: 188 ms, Speed: 0.01 M/s, Resolution: None
Name: 湖南卫视, URL: http://[2409:8087:5e00:24::1e]:6060/000000001000/1000000001000009115/index.m3u8?channel-id=ystenlive&Contentid=1000000001000009115&livemode=1&stbId=3$订阅源, Date: None, Delay: 188 ms, Speed: 0.01 M/s, Resolution: None
Name: 湖南卫视, URL: http://[2409:8087:5e00:24::11]:6060/200000001898/460000089800010224/$订阅源, Date: None, Delay: 189 ms, Speed: 0.01 M/s, Resolution: None
Name: 湖南卫视, URL: http://[2409:8087:5e00:24::1e]:6060/000000001000/1000000001000009115/1.m3u8$订阅源, Date: None, Delay: 188 ms, Speed: 0.01 M/s, Resolution: None
Name: 湖南卫视, URL: http://[2409:8087:5e00:24::1e]:6060/200000001898/460000089800010058/1.m3u8?$订阅源, Date: None, Delay: 188 ms, Speed: 0.01 M/s, Resolution: None
Name: 湖南卫视, URL: http://[2409:8087:5e00:24::1e]:6060/200000001898/460000089800010058/$订阅源, Date: None, Delay: 188 ms, Speed: 0.01 M/s, Resolution: None
Name: 湖南卫视, URL: http://[2409:8087:5e00:24::1e]:6060/200000001898/460000089800010224/1.m3u8$订阅源, Date: None, Delay: 188 ms, Speed: 0.01 M/s, Resolution: None
Name: 湖南卫视, URL: http://[2409:8087:5e00:24::1e]:6060/000000001000/1000000001000032695/1.m3u8$订阅源, Date: None, Delay: 188 ms, Speed: 0.01 M/s, Resolution: None

```

**Comment by Guovin** [comment]
> > > 我这也差不多情况，ipv6的地址测速结果不准确，基本都是0.1-0.3M/s左右，但实际访问看的话速度是正常的
> > 
> > 
> > 测速日志的ipv6是有显示速率的吗？没有像上面这样都是0吧？
> 
> 速率有可能出现0，试了几次大概都是统一的速率像0.01或0这样，v4地址的测速正常。
> 
> ```
> Name: 湖南卫视, URL: http://[2409:8087:5e00:24::1e]:6060/200000001898/460000089800010224/$订阅源, Date: None, Delay: 188 ms, Speed: 0.01 M/s, Resolution: None
> Name: 湖南卫视, URL: http://[2409:8087:5e00:24::1e]:6060/200000001898/460000089800010058/1.m3u8$订阅源, Date: None, Delay: 188 ms, Speed: 0.01 M/s, Resolution: None
> Name: 湖南卫视, URL: http://[2409:8087:5e00:24::1e]:6060/200000001898/460000089800010058/index.m3u8$订阅源, Date: None, Delay: 188 ms, Speed: 0.01 M/s, Resolution: None
> Name: 湖南卫视, URL: http://[2409:8087:5e00:24::1e]:6060/000000001000/1000000001000009115/index.m3u8?channel-id=ystenlive&Contentid=1000000001000009115&livemode=1&stbId=3$订阅源, Date: None, Delay: 188 ms, Speed: 0.01 M/s, Resolution: None
> Name: 湖南卫视, URL: http://[2409:8087:5e00:24::11]:6060/200000001898/460000089800010224/$订阅源, Date: None, Delay: 189 ms, Speed: 0.01 M/s, Resolution: None
> Name: 湖南卫视, URL: http://[2409:8087:5e00:24::1e]:6060/000000001000/1000000001000009115/1.m3u8$订阅源, Date: None, Delay: 188 ms, Speed: 0.01 M/s, Resolution: None
> Name: 湖南卫视, URL: http://[2409:8087:5e00:24::1e]:6060/200000001898/460000089800010058/1.m3u8?$订阅源, Date: None, Delay: 188 ms, Speed: 0.01 M/s, Resolution: None
> Name: 湖南卫视, URL: http://[2409:8087:5e00:24::1e]:6060/200000001898/460000089800010058/$订阅源, Date: None, Delay: 188 ms, Speed: 0.01 M/s, Resolution: None
> Name: 湖南卫视, URL: http://[2409:8087:5e00:24::1e]:6060/200000001898/460000089800010224/1.m3u8$订阅源, Date: None, Delay: 188 ms, Speed: 0.01 M/s, Resolution: None
> Name: 湖南卫视, URL: http://[2409:8087:5e00:24::1e]:6060/000000001000/1000000001000032695/1.m3u8$订阅源, Date: None, Delay: 188 ms, Speed: 0.01 M/s, Resolution: None
> ```
收到，谢谢~

**Comment by Guovin** [comment]
该问题已修复，请更新
