### ISSUE TITLE
今天使用docker版本进行安装配置后，强制ipv6_support = True后，代码里check_ipv6_support()方法依然会执行，依然认为我没有ipv6

### ISSUE THREAD

**Issue by busymilk** [Guovin/iptv-api#698]
### Don't skip these steps

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field
- [X] I have checked through the search that there are no similar issues that already exist
- [X] I will not submit any issues that are not related to this project

### Occurrence environment

- [ ] Workflow
- [ ] GUI
- [X] Docker
- [ ] Command line

### Bug description

Checking if your network supports IPv6...

Your network does not support IPv6

我只在config.ini末尾添加了以下内容：
ipv6_support = True
open_update_time = False

输出的结果里open_update_time是起效了的，是docker的版本没有更新么？

**Comment by Guovin** [comment]
配置默认就含有ipv6_support，直接在原配置字段上修改，不要在后面追加重复字段

**Comment by busymilk** [comment]
> 配置默认就含有ipv6_support，直接在原配置字段上修改，不要在后面追加重复字段

docker的默认配置并没有这个字段，我搜索过了，只有我在末尾添加的ipv6_support字段

**Comment by Guovin** [comment]
> > 配置默认就含有ipv6_support，直接在原配置字段上修改，不要在后面追加重复字段
> 
> docker的默认配置并没有这个字段，我搜索过了，只有我在末尾添加的ipv6_support字段

你应该是使用了挂载命令，主机的旧配置文件没有删除，导致同步到容器了
