### ISSUE TITLE
使用docker版本生成结果，配置选择移除更新时间字段，依然会报解析失败tvbox几个版本，还有我的电视·O 都试过了

### ISSUE THREAD

**Issue by busymilk** [Guovin/iptv-api#699]
### Don't skip these steps

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field
- [X] I have checked through the search that there are no similar issues that already exist
- [X] I will not submit any issues that are not related to this project

### Occurrence environment

- [ ] Workflow
- [ ] GUI
- [X] Docker
- [ ] Command line

### Bug description

如题，已经在别人提出的类似问题中都试过了，tvbox几个版本都是解析失败，使用的是docker生成的result。

**Comment by busymilk** [comment]
> 貌似tvboxosc对很多接口都是解析失败，能找到可以解析成功的给我看看吗？否则先更换使用ok影视、影视仓等播放软件

影视仓也试过了，也是不行

**Comment by Guovin** [comment]
> > 貌似tvboxosc对很多接口都是解析失败，能找到可以解析成功的给我看看吗？否则先更换使用ok影视、影视仓等播放软件
> 
> 影视仓也试过了，也是不行

我试了最新版的影视仓5.0.46使用m3u和txt都可以播放

**Comment by yst1982** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Guovin** [comment]
同时，最新版更新时间的接口地址已经使用首个频道的接口地址，开启显示更新时间不会导致解析问题。

**Comment by bloy123** [comment]
影视仓5.0.46 在哪儿下呢

**Comment by Guovin** [comment]
> 影视仓5.0.46 在哪儿下呢

非本项目的问题请不要在此讨论

**Comment by bloy123** [comment]
哦哦 搞定了
