### ISSUE TITLE
相同频道在各源中不同名，模板应该怎样编辑

### ISSUE THREAD

**Issue by iNewWay** [Guovin/iptv-api#702]
### Don't skip these steps

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field
- [X] I have checked through the search that there are no similar issues that already exist
- [X] I will not submit any issues that are not related to this project

### Occurrence environment

- [ ] Workflow
- [ ] GUI
- [ ] Docker
- [ ] Command line

### Question description

比如各个源里CCTV1的名称各不相同：
CCTV1，CCTV-1，CCTV1综合，CCTV-1综合……
这样的同一个频道而名称不同的情况，模板内应该怎样编辑？

**Comment by Guovin** [comment]
不需要特殊处理，CCTV类频道已经做过处理，上述名称随意选一个写入模板即可

**Comment by 389377616** [comment]
> 不需要特殊处理，CCTV类频道已经做过处理，上述名称随意选一个写入模板即可

最近发现有些CCTV频道没有被合并，比如CCTV1，CCTV2，这样的频道名字没有被合并到CCTV-1，CCTV-2里，我打开了配置里的
# 开启保留所有检索结果，会保留非模板频道名称的结果，推荐手动维护时开启; 可选值: True, False | Enable to keep all search results, will keep the results of non-template channel names, it is recommended to enable when manually maintaining; Optional values: True, False
open_keep_all = True
这样模板里没有的频道结果全部会保留到最下边其它频道的分类里，我在里边发现了很多CCTV1，CCTV2，CCTV3这样的频道.

**Comment by Guovin** [comment]
> > 不需要特殊处理，CCTV类频道已经做过处理，上述名称随意选一个写入模板即可
> 
> 最近发现有些CCTV频道没有被合并，比如CCTV1，CCTV2，这样的频道名字没有被合并到CCTV-1，CCTV-2里，我打开了配置里的
> 
> # 开启保留所有检索结果，会保留非模板频道名称的结果，推荐手动维护时开启; 可选值: True, False | Enable to keep all search results, will keep the results of non-template channel names, it is recommended to enable when manually maintaining; Optional values: True, False
> open_keep_all = True 这样模板里没有的频道结果全部会保留到最下边其它频道的分类里，我在里边发现了很多CCTV1，CCTV2，CCTV3这样的频道.

这并不代表没有合并，开启保留模式的作用是保留了与模板中频道名称非完全匹配的频道至其它频道分类中，便于自行维护，这样做是为了能观察到是否有频道被错误匹配了。

**Comment by w6566** [comment]
这个匹配机制后续可以改为自定义吗，就是比如A频道，我可以自己设置A1、A2、a1、a2匹配到A频道里




wj0321
***@***.***

**Comment by Guovin** [comment]
> 这个匹配机制后续可以改为自定义吗，就是比如A频道，我可以自己设置A1、A2、a1、a2匹配到A频道里
> 
> 
> 
> 
> wj0321
> ***@***.***

#733
