### ISSUE TITLE
生成直播源自动跳台，不稳定！

### ISSUE THREAD

**Issue by tianniao886** [Guovin/iptv-api#703]
### Don't skip these steps

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field
- [X] I have checked through the search that there are no similar issues that already exist
- [X] I will not submit any issues that are not related to this project

### Occurrence environment

- [ ] Workflow
- [ ] GUI
- [X] Docker
- [ ] Command line

### Question description

Docker lite版，生成的ipv6直播源，晚上看直播会自动跳台..不稳定，几乎每天都会有这种情况。换过播放器也没啥变化。用https://m3u.ibert.me/fmml_ipv6.m3u同样台却很稳定。是不是筛选源的逻辑有问题啊？能不能优化下？

**Comment by Guovin** [comment]
你的网络是支持ipv6吗？如果不支持，会自动跳过ipv6切换到其它源

**Comment by tianniao886** [comment]
支持ipv6网络。如：看cctv8就会常出现看个十来分钟跳出。有时候会时间久一些。config文件中已经设置不生成ipv4频道。你看看设置有问题吗？
![屏幕截图 2024-12-19 164348](https://github.com/user-attachments/assets/d56dfb04-99cf-4308-8a12-151cdfeb9431)

**Comment by Guovin** [comment]
> 支持ipv6网络。如：看cctv8就会常出现看个十来分钟跳出。有时候会时间久一些。config文件中已经设置不生成ipv4频道。你看看设置有问题吗？
> 
> ![屏幕截图 2024-12-19 164348](https://private-user-images.githubusercontent.com/101009314/397299570-cdb012c1-5e67-42dc-9449-21090a240aa7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MDAzODEsIm5iZiI6MTczNDYwMDA4MSwicGF0aCI6Ii8xMDEwMDkzMTQvMzk3Mjk5NTcwLWNkYjAxMmMxLTVlNjctNDJkYy05NDQ5LTIxMDkwYTI0MGFhNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOVQwOTIxMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjBjMDQ0OGMxOWM3YmE0ZTYxNjViMjJjYjA0ZGFhOTYyODVjMDU1YWYxNDFjMjk4ZDViYWU3ZWQ4MTkzYjc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hAn4EGDavEhbdBFESfbait2B8raoVWHb0LG10r3qE5U)

这似乎是旧版的配置文件，有拉取最新镜像吗？需要删除主机的旧配置文件，否则挂载会同步到容器内

**Comment by tianniao886** [comment]
好的，我从新拉取下！谢谢

**Comment by Guovin** [comment]
我也有注意到有些接口没有达到超时换源的时间就切换了，这个问题的原因还是很大程度取决于接口和播放器。

**Comment by w1365258** [comment]
这明显是你自己网络问题，跟生成结果有毛关系。频道地址是绝对地址，要么不能用，要么网速不好

**Comment by tianniao886** [comment]
生成的频道质量不佳造成的跳台。新版Docker版已修复。
