### ISSUE TITLE
请问config.ini配置文件是否可以添加注释文字

### ISSUE THREAD

**Issue by 389377616** [Guovin/iptv-api#704]
### Don't skip these steps

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field
- [X] I have checked through the search that there are no similar issues that already exist
- [X] I will not submit any issues that are not related to this project

### Occurrence environment

- [ ] Workflow
- [ ] GUI
- [ ] Docker
- [X] Command line

### Question description

config.ini里的参数都是英文的，我英文不太好，每次想修改参数的时候还都去https://github.com/Guovin/iptv-api/blob/master/docs/config.md 这个页面查看参数说明，这样我感觉太麻烦，我想把每个参数对应的中文参数说明用注释的方式写在每一行参数的上边写在配置文件里，这样修改参数就可以更加清晰明白，但是我不清楚你这个配置文件支不支持写入注释，用什么符号可以作为注释标记

**Comment by Guovin** [comment]
支持注释，后续我会补充

**Comment by Guovin** [comment]
已增加
