### ISSUE TITLE
在Sorting阶段卡在最后啦

### ISSUE THREAD

**Issue by zhycn9033** [Guovin/iptv-api#705]
### Don't skip these steps

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field
- [X] I have checked through the search that there are no similar issues that already exist
- [X] I will not submit any issues that are not related to this project

### Occurrence environment

- [X] Workflow
- [ ] GUI
- [ ] Docker
- [ ] Command line

### Bug description

还以为自己的配置有问题卡了，后来发现作者的也卡啦，辛苦弄一下吧。
![screenshot-1734574023174](https://github.com/user-attachments/assets/8c3bfb61-dc18-489f-aaeb-938cc8ef0683)

**Comment by Guovin** [comment]
该问题正在排查处理

**Comment by Guovin** [comment]
已修复，更新一下代码

**Comment by zhycn9033** [comment]
OK了

**Comment by zhycn9033** [comment]
OK了
