### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by wudixxqq** [Guovin/iptv-api#709]
### Don't skip these steps / 不要跳过这些步骤

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field / 我明白，如果我“故意”删除或跳过任何强制性的\*字段，我将被**封锁**
- [X] I have checked through the search that there are no similar issues that already exist / 我已经通过搜索仔细检查过没有存在已经创建的相似问题
- [X] I will not submit any issues that are not related to this project / 我不会提交任何与本项目无关的问题

### Occurrence environment / 触发环境

- [ ] Workflow / 工作流
- [ ] GUI / 软件
- [X] Docker
- [ ] Command line / 命令行

### Bug description / 具体描述

docket完整版。同步回来的播放源。
地址后面会有汉字~湖北酒店源~。
直接导入到播放器中，无法播放噢

**Comment by wudixxqq** [comment]
docker完整版同步回来的播放源地址后面会有汉字湖北酒店源。直接导入播放器无法播放

**Comment by Guovin** [comment]
提交bug请补充完整标题；修改配置open_url_info = False可以移除接口文字信息
