### ISSUE TITLE
[Bug]: 为什么有些接口明明质量很高，排序时却测不出各种指标呢

### ISSUE THREAD

**Issue by zhycn9033** [Guovin/iptv-api#714]
### Don't skip these steps | 不要跳过这些步骤

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field | 我明白，如果我“故意”删除或跳过任何强制性的\*字段，我将被**封锁**
- [X] I have checked through the search that there are no similar issues that already exist | 我已经通过搜索仔细检查过没有存在已经创建的相似问题
- [X] I will not submit any issues that are not related to this project | 我不会提交任何与本项目无关的问题

### Occurrence environment | 触发环境

- [X] Workflow | 工作流
- [ ] GUI | 软件
- [ ] Docker
- [ ] Command line | 命令行

### Bug description | 具体描述

Name: CCTV-1, URL: http://d954f9.tv.netsite.cc/proxy/1387573383/1387573383.m3u8$订阅源, Date: None, Delay: None ms, Speed: 0.00 M/s, Resolution: None
比如这种，明明很优质的接口，但延迟和速度都测不出来，导致被废弃

**Comment by tianniao886** [comment]
确实，ipv4接口筛选出的频道卡顿基本不能用。有些质量好的被淘汰。只能手动测试接口。ipv6接口筛选机制有待优化。

**Comment by Guovin** [comment]
这并不是程序的问题，因为工作流的网络环境跟你本地的环境并不一致，工作流的服务器是在国外，访问国内资源可能会有影响，导致测速出现误差，我尝试本地对这个接口进行测速，显示速度12M/s，延迟57ms。如果对测速有要求建议本地运行或将这部分接口加入白名单。

**Comment by zhycn9033** [comment]
原来如此，谢谢
