### ISSUE TITLE
[Bug]: Sorting的阶段又卡了

### ISSUE THREAD

**Issue by zhycn9033** [Guovin/iptv-api#719]
### Don't skip these steps | 不要跳过这些步骤

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field | 我明白，如果我“故意”删除或跳过任何强制性的\*字段，我将被**封锁**
- [X] I have checked through the search that there are no similar issues that already exist | 我已经通过搜索仔细检查过没有存在已经创建的相似问题
- [X] I will not submit any issues that are not related to this project | 我不会提交任何与本项目无关的问题

### Occurrence environment | 触发环境

- [X] Workflow | 工作流
- [ ] GUI | 软件
- [ ] Docker
- [ ] Command line | 命令行

### Bug description | 具体描述

又卡住了

**Comment by Guovin** [comment]
已修复
