### ISSUE TITLE
[Bug]: Can not load response cookies: Illegal key session820/qualitor820'

### ISSUE THREAD

**Issue by crylcy** [Guovin/iptv-api#728]
### Don't skip these steps | 不要跳过这些步骤

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field | 我明白，如果我“故意”删除或跳过任何强制性的\*字段，我将被**封锁**
- [X] I have checked through the search that there are no similar issues that already exist | 我已经通过搜索仔细检查过没有存在已经创建的相似问题
- [X] I will not submit any issues that are not related to this project | 我不会提交任何与本项目无关的问题

### Occurrence environment | 触发环境

- [ ] Workflow | 工作流
- [ ] GUI | 软件
- [X] Docker
- [ ] Command line | 命令行

### Bug description | 具体描述

停住了，运行52分钟没有结果，仍然提示耐心等待

### Error log | 报错日志

[guovern-iptv-api1.zip](https://github.com/user-attachments/files/18227596/guovern-iptv-api1.zip)
大佬，感觉使用docker卡住了，附件是日记，标题是卡住的地方。谢谢大佬~！

**Comment by Guovin** [comment]
#719 应该是同一个问题，但并不是标题的提示内容导致的，那个提示忽略即可，不影响运行。该问题已经修复，待会更新镜像后重新拉取即可。

**Comment by crylcy** [comment]
大佬这么快就回复了，谢谢谢谢~！
