### ISSUE TITLE
[Bug]:播放地址有中文，无法播放

### ISSUE THREAD

**Issue by wudixxqq** [Guovin/iptv-api#734]
### Don't skip these steps | 不要跳过这些步骤

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field | 我明白，如果我“故意”删除或跳过任何强制性的\*字段，我将被**封锁**
- [X] I have checked through the search that there are no similar issues that already exist | 我已经通过搜索仔细检查过没有存在已经创建的相似问题
- [X] I will not submit any issues that are not related to this project | 我不会提交任何与本项目无关的问题

### Occurrence environment | 触发环境

- [ ] Workflow | 工作流
- [ ] GUI | 软件
- [X] Docker
- [ ] Command line | 命令行

### Bug description | 具体描述

docker  lite版
获取地址后
播放地址后面有中文
例如http://1.30.24.181:9901/tsfile/live/0001_1.m3u8$订阅源

$字符会被播放器认为是播放地址，导致无法播放。
更换成#字符  正常播放。

### Error log | 报错日志

docker  lite版
获取地址后
播放地址后面有中文
例如http://1.30.24.181:9901/tsfile/live/0001_1.m3u8$订阅源

$字符会被播放器认为是播放地址，导致无法播放。
更换成#字符  正常播放。

**Comment by Guovin** [comment]
播放器问题，可修改配置open_url_info = False不输出接口信息
