### ISSUE TITLE
[Bug]: 获取接口数量和我预期不一样是什么情况？

### ISSUE THREAD

**Issue by 389377616** [Guovin/iptv-api#735]
### Don't skip these steps | 不要跳过这些步骤

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field | 我明白，如果我“故意”删除或跳过任何强制性的\*字段，我将被**封锁**
- [X] I have checked through the search that there are no similar issues that already exist | 我已经通过搜索仔细检查过没有存在已经创建的相似问题
- [X] I will not submit any issues that are not related to this project | 我不会提交任何与本项目无关的问题

### Occurrence environment | 触发环境

- [ ] Workflow | 工作流
- [ ] GUI | 软件
- [X] Docker
- [ ] Command line | 命令行

### Bug description | 具体描述

我的预期是订阅源6个3个ipv6源，3个ipv4源，然后三个酒店源，结果输出结果是这样的
![源](https://github.com/user-attachments/assets/3f07559a-43a4-47f5-b69b-abb891df02a8)

### Error log | 报错日志

配置文件
[Settings]
# 开启浏览器运行，若更新无数据可开启此模式，较消耗性能; 可选值: True, False | Enable browser execution, If there are no updates, this mode can be enabled, which consumes more performance; Optional values: True, False
open_driver = False
# 开启无结果频道分类，自动归类至底部; 可选值: True, False | Enable empty category, automatically classified to the bottom; Optional values: True, False
open_empty_category = False
# 开启分辨率过滤，低于最小分辨率（min_resolution）的接口将会被过滤; 可选值: True, False | Enable resolution filtering, interfaces below the minimum resolution (min_resolution) will be filtered; Optional values: True, False
open_filter_resolution = False
# 开启速率过滤，低于最小速率（min_speed）的接口将会被过滤; 可选值: True, False | Enable rate filtering, interfaces below the minimum rate (min_speed) will be filtered; Optional values: True, False
open_filter_speed = True
# 开启酒店源功能，关闭后所有酒店源工作模式都将关闭; 可选值: True, False | Enable hotel source function, after closing, all hotel source working modes will be closed; Optional values: True, False
open_hotel = True
# 开启 Foodie 酒店源工作模式; 可选值: True, False | Enable Foodie hotel source working mode; Optional values: True, False
open_hotel_foodie = True
# 开启 FOFA、ZoomEye 酒店源工作模式; 可选值: True, False | Enable FOFA, ZoomEye hotel source working mode; Optional values: True, False
open_hotel_fofa = True
# 开启保留所有检索结果，会保留非模板频道名称的结果，推荐手动维护时开启; 可选值: True, False | Enable to keep all search results, will keep the results of non-template channel names, it is recommended to enable when manually maintaining; Optional values: True, False
open_keep_all = False
# 开启转换生成 m3u 文件类型结果链接，支持显示频道图标; 可选值: True, False | Enable to convert and generate m3u file type result links, support display channel icons; Optional values: True, False
open_m3u_result = False
# 开启组播源功能，关闭后所有组播源工作模式都将关闭; 可选值: True, False | Enable multicast source function, after closing, all multicast source working modes will be closed; Optional values: True, False
open_multicast = False
# 开启 Foodie 组播源工作模式; 可选值: True, False | Enable Foodie multicast source working mode; Optional values: True, False
open_multicast_foodie = False
# 开启 FOFA 组播源工作模式; 可选值: True, False | Enable FOFA multicast source working mode; Optional values: True, False
open_multicast_fofa = False
# 开启关键字搜索源功能; 可选值: True, False | Enable keyword search source function; Optional values: True, False
open_online_search = True
# 开启代理，自动获取免费可用代理，若更新无数据可开启此模式; 可选值: True, False | Enable proxy, automatically obtain free available proxy, If there are no updates, this mode can be enabled; Optional values: True, False
open_proxy = False
# 开启查询请求，数据来源于网络（仅针对酒店源与组播源）; 可选值: True, False | Enable query request, data comes from the network (only for hotel source and multicast source); Optional values: True, False
open_request = True
# 开启页面服务，用于控制是否启动结果页面服务；如果使用青龙等平台部署，有专门设定的定时任务，需要更新完成后停止运行，可以关闭该功能; 可选值: True, False | Enable page service, used to control whether to start the result page service; If you use platforms such as Qinglong for deployment, there are special scheduled tasks, you need to stop running after the update is completed, you can turn off this function; Optional values: True, False
open_service = True
# 开启排序功能（响应速度、日期、分辨率）; 可选值: True, False | Enable sorting function (response speed, date, resolution); Optional values: True, False
open_sort = True
# 开启订阅源功能; 可选值: True, False | Enable subscription source function; Optional values: True, False
open_subscribe = True
# 开启更新，用于控制是否更新接口，若关闭则所有工作模式（获取接口和测速）均停止; 可选值: True, False | Enable update, used to control whether to update the interface, if closed, all working modes (get interface and speed measurement) will stop; Optional values: True, False
open_update = True
# 开启显示更新时间; 可选值: True, False | Enable display update time; Optional values: True, False
open_update_time = False
# 开启显示接口说明信息，用于控制是否显示分辨率、接口协议类型等信息，为$符号后的内容，播放软件使用该信息对接口进行描述; 可选值: True, False | Enable display interface description information, used to control whether to display resolution, interface protocol type and other information, the information after the $ symbol, the playback software uses this information to describe the interface; Optional values: True, False
open_url_info = True
# 开启使用本地缓存数据，适用于查询请求失败场景（仅针对酒店源与组播源）; 可选值: True, False | Enable to use local cached data, suitable for query request failure scenarios (only for hotel source and multicast source); Optional values: True, False
open_use_cache = False
# 开启使用历史更新结果（包含模板与结果文件的接口），合并至本次更新中; 可选值: True, False | Enable to use historical update results (including interfaces of templates and result files), merged into this update; Optional values: True, False
open_use_old_result = False
# 页面服务端口，用于控制页面服务的端口号; 默认值: 8000 | Page service port, used to control the port number of the page service; Default value: 8000
app_port = 8000
# 生成结果文件路径; 默认值: output/result.txt | Generate result file path; Default value: output/result.txt
final_file = output/result.txt
# 结果中偏好的酒店源接口数量 | Preferred number of hotel source interfaces in the result
hotel_num = 3
# 酒店地区获取分页数量 | Number of hotel region acquisition pages
hotel_page_num = 1
# 酒店源地区列表，"全部"表示所有地区 | Hotel source region list, "all" means all regions
hotel_region_list = 全部
# 结果中偏好的 IPv4 接口数量 | Preferred number of IPv4 interfaces in the result
ipv4_num = 3
# 结果中偏好的 IPv6 接口数量 | Preferred number of IPv6 interfaces in the result
ipv6_num = 3
# 强制认为当前网络支持IPv6，跳过检测 | Force to consider that the current network supports IPv6, skip detection
ipv6_support = False
# 生成结果中接口的协议类型，可选值：ipv4、ipv6、全部、all | Protocol type of the interface in the generated result, optional values: ipv4, ipv6, 全部, all
ipv_type = all
# 接口协议类型偏好，优先将该类型的接口排在结果前面，可选值：IPv4、IPv6、自动、auto | Interface protocol type preference, prefer to put this type of interface in front of the result, optional values: IPv4, IPv6, 自动, auto
ipv_type_prefer = 自动
# 接口最小分辨率，需要开启 open_filter_resolution 才能生效 | Minimum resolution of the interface, need to enable open_filter_resolution to take effect
min_resolution = 1920x1080
# 接口最小速率（单位M/s），需要开启 open_filter_speed 才能生效 | Minimum rate of the interface (unit M/s), need to enable open_filter_speed to take effect
min_speed = 0.3
# 结果中偏好的组播源接口数量 | Preferred number of multicast source interfaces in the result
multicast_num = 0
# 组播地区获取分页数量 | Number of multicast region acquisition pages
multicast_page_num = 1
# 组播源地区列表，"全部"表示所有地区 | Multicast source region list, "all" means all regions
multicast_region_list = 全部
# 结果中偏好的关键字搜索接口数量 | Preferred number of keyword search interfaces in the result
online_search_num = 3
# 关键字搜索频道获取分页数量 | Number of keyword search channel acquisition pages
online_search_page_num = 1
# 结果偏好的接口来源，结果优先按该顺序进行排序，hotel：酒店源，multicast：组播源，subscribe：订阅源，online_search：关键字搜索 | Preferred interface source of the result, the result is sorted in this order, hotel: hotel source, multicast: multicast source, subscribe: subscription source, online_search: keyword search
origin_type_prefer = subscribe,hotel,online_search,multicast
# 获取最近时间范围内更新的接口（单位天），适当减小可避免出现匹配问题 | Get the interface updated within the recent time range (unit day), appropriately reducing can avoid matching problems
recent_days = 30
# 查询请求超时时长，单位秒(s)，用于控制查询接口文本链接的超时时长以及重试时长，调整此值能优化更新时间 | Query request timeout duration, unit seconds (s), used to control the timeout duration and retry duration of querying the interface text link, adjusting this value can optimize the update time
request_timeout = 10
# 单个接口测速超时时长，单位秒(s)；数值越大测速所属时间越长，能提高获取接口数量，但质量会有所下降；数值越小测速所需时间越短，能获取低延时的接口，质量较好；调整此值能优化更新时间 | Single interface speed measurement timeout duration, unit seconds (s); The larger the value, the longer the speed measurement time, which can increase the number of interfaces obtained, but the quality will decrease; The smaller the value, the shorter the speed measurement time, which can obtain interfaces with low latency and better quality; Adjusting this value can optimize the update time
sort_timeout = 6
# 模板文件路径， 默认值: config/demo.txt | Template file path, Default value: config/demo.txt
source_file = config/demo.txt
# 结果中偏好的订阅源接口数量 | Preferred number of subscription source interfaces in the result
subscribe_num = 9
# 单个频道接口数量 | Number of interfaces per channel
urls_limit = 25

**Comment by Guovin** [comment]
这是因为经测速过滤后，只有订阅源满足速率等条件，其它不满足的过滤了。

**Comment by 389377616** [comment]
接口最小速率单个接口测速超时时长

> 这是因为经测速过滤后，只有订阅源满足速率等条件，其它不满足的过滤了。

意思是得把接口最小速率设置的低一些，单个接口测速超时时长参数的设置的大一些？但是数量也不对劲啊，结果中偏好的 IPv6 接口和结果中偏好的 IPv4 接口我设置的都是3，两种接口现在加起来怎么那么多了

**Comment by Guovin** [comment]
> 接口最小速率单个接口测速超时时长
> 
> > 这是因为经测速过滤后，只有订阅源满足速率等条件，其它不满足的过滤了。
> 
> 意思是得把接口最小速率设置的低一些，单个接口测速超时时长参数的设置的大一些？但是数量也不对劲啊，结果中偏好的 IPv6 接口和结果中偏好的 IPv4 接口我设置的都是3，两种接口现在加起来怎么那么多了

默认开启了补偿模式open_supply，结果数量不足时会自动补充可能可播放的结果。

**Comment by 389377616** [comment]
> > 接口最小速率单个接口测速超时时长
> > > 这是因为经测速过滤后，只有订阅源满足速率等条件，其它不满足的过滤了。
> > 
> > 
> > 意思是得把接口最小速率设置的低一些，单个接口测速超时时长参数的设置的大一些？但是数量也不对劲啊，结果中偏好的 IPv6 接口和结果中偏好的 IPv4 接口我设置的都是3，两种接口现在加起来怎么那么多了
> 
> 默认开启了补偿模式open_supply，结果数量不足时会自动补充可能可播放的结果。

好的，我修改下速率和超时参数再试试看
