### ISSUE TITLE
[Bug]: 最新版代码执行报错

### ISSUE THREAD

**Issue by WongMinHo** [Guovin/iptv-api#744]
### Don't skip these steps | 不要跳过这些步骤

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field | 我明白，如果我“故意”删除或跳过任何强制性的\*字段，我将被**封锁**
- [X] I have checked through the search that there are no similar issues that already exist | 我已经通过搜索仔细检查过没有存在已经创建的相似问题
- [X] I will not submit any issues that are not related to this project | 我不会提交任何与本项目无关的问题

### Occurrence environment | 触发环境

- [ ] Workflow | 工作流
- [ ] GUI | 软件
- [X] Docker
- [X] Command line | 命令行

### Bug description | 具体描述

程序运行的时候报错

### Error log | 报错日志

  File "/iptv-api/main.py", line 215, in <module>
    loop.run_until_complete(update_source.start())
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/iptv-api/main.py", line 201, in start
    await self.main()
  File "/iptv-api/main.py", line 145, in main
    self.channel_data = await process_sort_channel_list(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/iptv-api/utils/channel.py", line 609, in process_sort_channel_list
    info_list = sort_urls(name, info_list, supply=open_supply, filter_speed=open_filter_speed,
                          min_speed=min_speed, filter_resolution=open_filter_resolution,
                          min_resolution=min_resolution, logger=logger)
  File "/iptv-api/utils/speed.py", line 335, in sort_urls
    not supply and filter_resolution and get_resolution_value(resolution) < min_resolution) or (
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'int' and 'str'

**Comment by Guovin** [comment]
已修复
