### ISSUE TITLE
关于白名单的使用方法？

### ISSUE THREAD

**Issue by FRANKASEE** [Guovin/iptv-api#750]
### Don't skip these steps | 不要跳过这些步骤

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field | 我明白，如果我“故意”删除或跳过任何强制性的\*字段，我将被**封锁**
- [X] I have checked through the search that there are no similar issues that already exist | 我已经通过搜索仔细检查过没有存在已经创建的相似问题
- [X] I will not submit any issues that are not related to this project | 我不会提交任何与本项目无关的问题

### Occurrence environment | 触发环境

- [ ] Workflow | 工作流
- [ ] GUI | 软件
- [X] Docker
- [ ] Command line | 命令行

### Bug description | 具体描述

新的白名单使用方法是和原来的一样在每个URL后面添加$!即可实现（如：广东珠江,http://xxx.m3u$/! ），还是直接在白名单内添加URL地址就可以？

针对整个订阅源想都设置白名单模式是直接添加订阅地址(如:[http://192.168.6.158:35456/txt/3），](http://192.168.6.158:35456/txt/3%EF%BC%89%EF%BC%8C)
还是逐行添加?
（如:CCTV1,http://192.168.6.158:35455/gaoma/cctv1.m3u8
CCTV1,http://192.168.6.158:35455/itv/6000000001000029752.m3u8?cdn=wasusyt
CCTV1-50-FPS,http://192.168.6.158:35455/itv/5000000004000002226.m3u8?cdn=bestzb
CCTV1-HEVC,http://192.168.6.158:35455/itv/1000000005000265001.m3u8?cdn=ystenlive
CCTV2-高码,http://192.168.6.158:35455/gaoma/cctv2.m3u8
CCTV2,http://192.168.6.158:35455/itv/1000000001000023315.m3u8?cdn=ystenlive
CCTV2-50-FPS,http://192.168.6.158:35455/itv/6000000001000014161.m3u8?cdn=wasusyt
CCTV2-HEVC,http://192.168.6.158:35455/itv/1000000001000023315.m3u8?cdn=ystenlive
CCTV2,[http://192.168.6.158:35455/tptv/G_CCTV-2-HD-265-8M.m3u8）](http://192.168.6.158:35455/tptv/G_CCTV-2-HD-265-8M.m3u8%EF%BC%89)

另外还有一个问题，http://aktv.top/live.txt 订阅内的港澳台接口，如果添加到订阅内会被检测到盗源，如何能直接添加到最终生成的文件内，而且不被检测盗源?

**Comment by Guovin** [comment]
1.建议使用白名单文件subscribe.txt，功能更完整，将整个订阅源内的全部接口作为白名单就将该订阅源地址添加到白名单文件subscribe.txt，demo.txt只能添加单个频道接口白名单。
2.你说的盗源应该是播放时显示的内容，这无法控制。
3.issues已经添加了支持与帮助的模板，该类问题应该使用该模板，而不是bug，请注意。
