### ISSUE TITLE
[Bug]: gui版本，提示我不支持IPV6,  但是实际我是支持IPV6访问的。

### ISSUE THREAD

**Issue by buzhixihuan2021** [Guovin/iptv-api#768]
### Don't skip these steps | 不要跳过这些步骤

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field | 我明白，如果我“故意”删除或跳过任何强制性的\*字段，我将被**封锁**
- [X] I have checked through the search that there are no similar issues that already exist | 我已经通过搜索仔细检查过没有存在已经创建的相似问题
- [X] I will not submit any issues that are not related to this project | 我不会提交任何与本项目无关的问题

### Occurrence environment | 触发环境

- [ ] Workflow | 工作流
- [X] GUI | 软件
- [ ] Docker
- [ ] Command line | 命令行

### Bug description | 具体描述

 GUI版本v1.5.8  win11    下载后 直接打开软件 不做其他任何设置，全部默认。 
提示不支持IPV6（这就导致不测速了）,  但是我的电脑是可以访问IPV6，可以观看IPV6的直播链接。打开http://ipv6-test.ch/ 也是显示支持IPV6的。

### Error log | 报错日志

Checking if your network supports IPv6...
Your network does not support IPv6, don't worry, these results will be saved

**Comment by Guovin** [comment]
如果你确认你的网络支持ipv6，可以勾选跳过ipv6检测后运行

**Comment by buzhixihuan2021** [comment]
![{783CF48C-A007-4E97-98AC-2BF9AF75708E}](https://github.com/user-attachments/assets/2ddf849d-167c-4d94-8d4a-c323b520a531)

勾选跳过ipv6检测后运行， sort.log 里面 我看测速是 0  ，但是实际却是可以播放  
Name: CCTV-8, URL: http://[2409:8087:1a0a:df::4036]:80/wh7f454c46tw1670555715_-98597522/ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226008/index.m3u8$订阅源, Date: None, Delay: 114 ms, Speed: 0.00 M/s, Resolution: 1920x1080
Name: CCTV-8, URL: http://[2409:8087:1a01:df::4077]/ottrrs.hl.chinamobile.com/yinhe/88888888/224/3221226008/index.m3u8$订阅源, Date: None, Delay: 250 ms, Speed: 0.00 M/s, Resolution: 1920x1080
